"""Management-ready, manually shared Excel workbooks.

These builders deliberately create fresh XLSX files.  They do not modify the
source workbook, keep external links, or copy raw worldwide call data into a
management attachment.
"""

from __future__ import annotations

from collections import Counter
from dataclasses import dataclass
from datetime import date, datetime, time
from pathlib import Path
from typing import Any, Iterable

import xlsxwriter
from openpyxl import load_workbook


COLORS = {
    "navy": "#0B1F33",
    "teal": "#007C83",
    "teal_light": "#DFF3F3",
    "gold": "#D6A84B",
    "canvas": "#F4F7F9",
    "ink": "#1F2933",
    "muted": "#536474",
    "line": "#D8E0E6",
    "blue": "#0563C1",
    "blue_light": "#E3F0FA",
    "green": "#1F7A53",
    "green_light": "#DDF3E8",
    "amber": "#A65F00",
    "amber_light": "#FFF1CC",
    "red": "#B42318",
    "red_light": "#FDE7E5",
    "white": "#FFFFFF",
}


def _clean(value: Any) -> str:
    return " ".join(str(value or "").strip().split())


def _number(value: Any) -> float | None:
    if value is None or value == "":
        return None
    try:
        return float(value)
    except (TypeError, ValueError):
        return None


def _safe_sheet_title(value: str) -> str:
    return value[:31].replace("/", "-").replace("[", "(").replace("]", ")")


class ManagementBook:
    """Small WFMHub design system shared by management workbooks."""

    def __init__(self, path: Path, title: str):
        path.parent.mkdir(parents=True, exist_ok=True)
        self.path = path
        self.workbook = xlsxwriter.Workbook(path)
        self.workbook.set_calc_mode("auto")
        self.workbook.set_properties({
            "title": title,
            "subject": "WFMHub manually shared management report",
            "author": "Anass ASSRI",
            "company": "WFM",
            "comments": "Generated by WFMHub; source files were not modified.",
        })
        add = self.workbook.add_format
        base = {"font_name": "Aptos", "font_size": 10, "font_color": COLORS["ink"]}
        self.fmt = {
            "title": add({"font_name": "Aptos Display", "font_size": 20, "bold": True,
                          "font_color": COLORS["white"], "bg_color": COLORS["navy"],
                          "valign": "vcenter", "indent": 1}),
            "subtitle": add({"font_name": "Aptos", "font_size": 9, "font_color": COLORS["white"],
                             "bg_color": COLORS["teal"], "valign": "vcenter", "indent": 1}),
            "section": add({**base, "font_name": "Aptos Display", "font_size": 12, "bold": True,
                            "font_color": COLORS["teal"], "bottom": 2,
                            "bottom_color": COLORS["gold"]}),
            "header": add({**base, "bold": True, "font_color": COLORS["white"],
                           "bg_color": COLORS["teal"], "text_wrap": True, "valign": "vcenter",
                           "bottom": 2, "bottom_color": COLORS["gold"]}),
            "body": add({**base, "bottom": 1, "bottom_color": COLORS["line"]}),
            "note": add({**base, "font_size": 9, "font_color": COLORS["muted"],
                         "text_wrap": True, "valign": "top"}),
            "input": add({**base, "font_color": COLORS["blue"], "bg_color": COLORS["blue_light"],
                          "bottom": 1, "bottom_color": COLORS["line"]}),
            "input_date": add({**base, "font_color": COLORS["blue"], "bg_color": COLORS["blue_light"],
                               "num_format": "yyyy-mm-dd", "bottom": 1,
                               "bottom_color": COLORS["line"]}),
            "input_datetime": add({**base, "font_color": COLORS["blue"], "bg_color": COLORS["blue_light"],
                                   "num_format": "yyyy-mm-dd hh:mm", "bottom": 1,
                                   "bottom_color": COLORS["line"]}),
            "date": add({**base, "num_format": "yyyy-mm-dd", "bottom": 1,
                         "bottom_color": COLORS["line"]}),
            "datetime": add({**base, "num_format": "yyyy-mm-dd hh:mm", "bottom": 1,
                             "bottom_color": COLORS["line"]}),
            "int": add({**base, "num_format": "#,##0", "bottom": 1,
                        "bottom_color": COLORS["line"]}),
            "dec": add({**base, "num_format": "#,##0.00", "bottom": 1,
                        "bottom_color": COLORS["line"]}),
            "pct": add({**base, "num_format": "0.0%", "bottom": 1,
                        "bottom_color": COLORS["line"]}),
            "money": add({**base, "num_format": '#,##0.00 "MAD"', "bottom": 1,
                          "bottom_color": COLORS["line"]}),
            "kpi_label": add({"font_name": "Aptos", "font_size": 9, "bold": True,
                              "font_color": COLORS["muted"], "bg_color": COLORS["canvas"],
                              "align": "center", "valign": "vcenter", "border": 1,
                              "border_color": COLORS["line"]}),
            "kpi": add({"font_name": "Aptos Display", "font_size": 20, "bold": True,
                        "font_color": COLORS["navy"], "bg_color": COLORS["white"],
                        "align": "center", "valign": "vcenter", "border": 1,
                        "border_color": COLORS["line"]}),
            "kpi_money": add({"font_name": "Aptos Display", "font_size": 18, "bold": True,
                              "font_color": COLORS["navy"], "bg_color": COLORS["white"],
                              "align": "center", "valign": "vcenter", "border": 1,
                              "border_color": COLORS["line"], "num_format": '#,##0.00 "MAD"'}),
            "kpi_pct": add({"font_name": "Aptos Display", "font_size": 20, "bold": True,
                            "font_color": COLORS["navy"], "bg_color": COLORS["white"],
                            "align": "center", "valign": "vcenter", "border": 1,
                            "border_color": COLORS["line"], "num_format": "0.0%"}),
            "good": add({**base, "bold": True, "font_color": COLORS["green"],
                         "bg_color": COLORS["green_light"], "align": "center"}),
            "warn": add({**base, "bold": True, "font_color": COLORS["amber"],
                         "bg_color": COLORS["amber_light"], "align": "center", "text_wrap": True}),
            "bad": add({**base, "bold": True, "font_color": COLORS["red"],
                        "bg_color": COLORS["red_light"], "align": "center", "text_wrap": True}),
            "white": add({**base, "font_color": COLORS["white"], "bg_color": COLORS["navy"]}),
        }

    def sheet(self, name: str, title: str, subtitle: str, last_col: int = 9):
        ws = self.workbook.add_worksheet(_safe_sheet_title(name))
        ws.hide_gridlines(2)
        ws.set_tab_color(COLORS["teal"])
        ws.merge_range(0, 0, 0, last_col, title, self.fmt["title"])
        ws.merge_range(1, 0, 1, last_col, subtitle, self.fmt["subtitle"])
        ws.set_row(0, 32)
        ws.set_row(1, 20)
        ws.set_zoom(90)
        return ws

    def banner(self, ws, row: int, first_col: int, last_col: int, text: str, kind: str) -> None:
        ws.merge_range(row, first_col, row, last_col, text, self.fmt[kind])
        ws.set_row(row, 27)

    def kpi(self, ws, first_col: int, row: int, label: str, value: Any,
            formula: str | None = None, kind: str = "kpi") -> None:
        ws.merge_range(row, first_col, row, first_col + 1, label, self.fmt["kpi_label"])
        if formula:
            ws.merge_range(row + 1, first_col, row + 2, first_col + 1, "", self.fmt[kind])
            ws.write_formula(row + 1, first_col, formula, self.fmt[kind], value)
        else:
            ws.merge_range(row + 1, first_col, row + 2, first_col + 1, value, self.fmt[kind])
        ws.set_row(row + 1, 25)
        ws.set_row(row + 2, 25)

    def close(self) -> Path:
        self.workbook.close()
        return self.path


@dataclass(frozen=True)
class BonusRule:
    population: str
    kpi: str
    direction: str
    tier1_bonus: float
    tier1_target: float
    tier2_bonus: float
    tier2_target: float


@dataclass
class BonusResult:
    core_ready: bool = False
    eligibility: str = ""
    earned: tuple[float, ...] = ()
    gross: float | None = None
    malus: float | None = None
    final: float | None = None
    reference: float | None = None
    proration: float | None = None
    scenario: float | None = None
    release: float | None = None
    status: str = ""
    issue: str = ""


DEFAULT_POLICIES = [
    ("Malus method", "Proportional", "Proportional | Percentage points", "HR / Compensation"),
    ("Extra PCS treatment", "Additive", "Additive | Replacement", "Operations / HR"),
    ("Target bonus rate basis", "Monthly", "Monthly | Annual", "HR / Payroll"),
    ("Proration denominator", "Calendar days", "Calendar days | Working days | Planned days", "HR / Payroll"),
    ("Absence treatment", "KPI only", "KPI only | Eligibility only | Both", "HR / Operations"),
    ("Achievement cap", 1.30, "0% to 200%", "HR / Compensation"),
    ("Rounding", "Centime", "Centime | Whole MAD", "Payroll"),
    ("Employee eligibility", "Active eligible population", "Policy reference required", "HR"),
]


def _header_row(ws, required: str, maximum: int = 20) -> int:
    for row in range(1, min(ws.max_row, maximum) + 1):
        if any(_clean(ws.cell(row, col).value).casefold() == required.casefold()
               for col in range(1, ws.max_column + 1)):
            return row
    raise ValueError(f"Could not find '{required}' header in sheet {ws.title}")


def _read_bonus_source(path: Path) -> tuple[list[dict[str, Any]], list[BonusRule], list[tuple[Any, ...]]]:
    if not path.exists():
        raise FileNotFoundError(path)
    workbook = load_workbook(path, read_only=True, data_only=True, keep_links=False)
    try:
        if "Raw_Data" not in workbook.sheetnames or "KPI_Config" not in workbook.sheetnames:
            raise ValueError("Bonus source must contain Raw_Data and KPI_Config sheets")
        raw = workbook["Raw_Data"]
        row = _header_row(raw, "Agent ID")
        headers = [_clean(raw.cell(row, col).value) for col in range(1, raw.max_column + 1)]
        rows: list[dict[str, Any]] = []
        for values in raw.iter_rows(min_row=row + 1, values_only=True):
            record = {headers[index]: value for index, value in enumerate(values) if index < len(headers)}
            if not _clean(record.get("Agent ID")):
                continue
            rows.append(record)

        config = workbook["KPI_Config"]
        config_row = _header_row(config, "Population")
        rules: list[BonusRule] = []
        for values in config.iter_rows(min_row=config_row + 1, values_only=True):
            if not _clean(values[0] if values else None) or not _clean(values[1] if len(values) > 1 else None):
                continue
            rules.append(BonusRule(
                _clean(values[0]), _clean(values[1]), _clean(values[2]).upper(),
                float(values[3] or 0), float(values[4] or 0),
                float(values[5] or 0), float(values[6] or 0),
            ))

        policies: list[tuple[Any, ...]] = []
        if "Policy_Decisions" in workbook.sheetnames:
            policy = workbook["Policy_Decisions"]
            policy_row = _header_row(policy, "Policy")
            for values in policy.iter_rows(min_row=policy_row + 1, values_only=True):
                if not _clean(values[0] if values else None):
                    continue
                policies.append(tuple(values[:7]))
        if not policies:
            policies = [(name, value, allowed, "", owner, "To validate", "")
                        for name, value, allowed, owner in DEFAULT_POLICIES]
        return rows, rules, policies
    finally:
        workbook.close()


def _bonus_value(record: dict[str, Any], *names: str) -> Any:
    for name in names:
        if name in record:
            return record[name]
    return None


def _bonus_period(records: list[dict[str, Any]]) -> str:
    periods = Counter(_clean(_bonus_value(row, "Period")) for row in records)
    periods.pop("", None)
    return periods.most_common(1)[0][0] if periods else datetime.now().strftime("%Y-%m")


def _policy_map(policies: Iterable[tuple[Any, ...]]) -> dict[str, Any]:
    return {_clean(row[0]): row[1] for row in policies}


def _earned(actual: float, rule: BonusRule) -> float:
    first = actual <= rule.tier1_target if rule.direction == "L" else actual >= rule.tier1_target
    second = actual <= rule.tier2_target if rule.direction == "L" else actual >= rule.tier2_target
    return rule.tier1_bonus if first else rule.tier2_bonus if second else 0.0


def _calculate_bonus(
    record: dict[str, Any],
    rules: list[BonusRule],
    policies: dict[str, Any],
    policies_ready: bool,
) -> BonusResult:
    population = _clean(_bonus_value(record, "Population"))
    actuals = [
        _number(_bonus_value(record, "AHT")),
        _number(_bonus_value(record, "Productivity")),
        _number(_bonus_value(record, "PCS Score")),
        _number(_bonus_value(record, "PCS % Participation", "PCS % (Participation)")),
        _number(_bonus_value(record, "QM")),
        _number(_bonus_value(record, "Abs%")),
    ]
    reference_override = _number(_bonus_value(record, "Reference Bonus Override")) or 0
    salary = _number(_bonus_value(record, "Monthly Fixed Salary")) or 0
    rate = _number(_bonus_value(record, "Target Bonus Rate")) or 0
    eligible_days = _number(_bonus_value(record, "Eligible Days"))
    scheduled_days = _number(_bonus_value(record, "Scheduled Days"))
    rule_map = {(rule.population, rule.kpi): rule for rule in rules}
    required = ("AHT", "Productivity", "PCS Score", "PCS % (Participation)", "QM", "Abs%")
    result = BonusResult()
    result.core_ready = (
        all(value is not None for value in actuals)
        and all((population, name) in rule_map for name in required)
        and (reference_override > 0 or (salary > 0 and rate > 0))
        and eligible_days is not None and scheduled_days is not None
        and 0 <= eligible_days <= scheduled_days and scheduled_days > 0
        and all(0 <= actuals[index] <= 1 for index in (3, 4, 5))
    )
    if not result.core_ready:
        result.status = "BLOCKED - INPUT"
        result.issue = "Missing, invalid, or unconfigured required input"
        return result
    scores = [_earned(float(value), rule_map[(population, name)]) for value, name in zip(actuals, required)]
    extra_rule = rule_map.get((population, "Extra Bonus (PCS Score)"))
    extra = _earned(float(actuals[2]), extra_rule) if extra_rule else 0.0
    absence_treatment = _clean(policies.get("Absence treatment", "KPI only"))
    if absence_treatment == "Eligibility only":
        scores[5] = 0.0
    absence_target = rule_map[(population, "Abs%")].tier1_target
    employment = _clean(_bonus_value(record, "Employment Status")) or "Not supplied"
    absence_eligible = float(actuals[5]) <= absence_target
    if employment.casefold() != "active":
        result.eligibility = "REVIEW"
    elif absence_treatment in {"Eligibility only", "Both"} and not absence_eligible:
        result.eligibility = "INELIGIBLE ABS"
    else:
        result.eligibility = "ELIGIBLE"
    extra_method = _clean(policies.get("Extra PCS treatment", "Additive"))
    base = sum(scores)
    gross = base + extra if extra_method == "Additive" else base - scores[2] + max(scores[2], extra)
    cap = _number(policies.get("Achievement cap")) or 1.30
    gross = min(gross, cap)
    voc = int(_number(_bonus_value(record, "VOC Detractor Count")) or 0)
    malus = {0: 0.0, 1: 0.10, 2: 0.20, 3: 0.50, 4: 0.75}.get(voc, 1.0)
    final = max(0.0, gross - malus) if _clean(policies.get("Malus method")) == "Percentage points" else gross * (1 - malus)
    reference = reference_override or salary * rate / (12 if _clean(policies.get("Target bonus rate basis")) == "Annual" else 1)
    proration = min(1.0, float(eligible_days) / float(scheduled_days))
    digits = 0 if _clean(policies.get("Rounding")) == "Whole MAD" else 2
    scenario = round(reference * proration * final, digits)
    data_status = _clean(_bonus_value(record, "Data Status"))
    result.earned = (*scores, extra)
    result.gross, result.malus, result.final = gross, malus, final
    result.reference, result.proration, result.scenario = reference, proration, scenario
    result.release = scenario if policies_ready and data_status == "VALIDATED" and result.eligibility == "ELIGIBLE" else None
    if result.eligibility != "ELIGIBLE":
        result.status = "BLOCKED - ELIGIBILITY"
    elif data_status != "VALIDATED":
        result.status = "BLOCKED - DATA"
    elif not policies_ready:
        result.status = "BLOCKED - POLICY"
    else:
        result.status = "READY"
    result.issue = "" if result.status == "READY" else result.status
    return result


def build_bonus_management(source: Path, output: Path) -> Path:
    """Rebuild a governed management bonus proposal from an existing source."""

    records, rules, policies = _read_bonus_source(source)
    period = _bonus_period(records)
    policy_values = _policy_map(policies)
    policies_ready = bool(policies) and all(
        len(row) > 5 and _clean(row[5]).casefold() == "validated" for row in policies
    )
    results = [_calculate_bonus(record, rules, policy_values, policies_ready) for record in records]
    capacity = max(250, len(records) + 25)
    book = ManagementBook(output, "Bonus Management Proposal")
    wb, f = book.workbook, book.fmt

    setup = book.sheet("SETUP", "Bonus management setup",
                       "Blue cells are the only operating inputs. One period controls the complete workbook.", 7)
    setup.set_column("A:A", 31)
    setup.set_column("B:B", 24)
    setup.set_column("C:H", 17)
    setup.write("A4", "Control", f["header"])
    setup.write("B4", "Value", f["header"])
    setup_rows = [
        ("Report period", period, "input"),
        ("Generated at", datetime.now(), "datetime"),
        ("Prepared by", "Anass ASSRI", "input"),
        ("Workbook version", "1.0", "body"),
    ]
    for offset, (label, value, fmt) in enumerate(setup_rows, 4):
        setup.write(offset, 0, label, f["body"])
        setup.write(offset, 1, value, f[fmt])
    setup.write(8, 0, "Policy release gate", f["body"])
    setup.write_formula(8, 1, '=IF(COUNTIF(tblPolicies[Status],"Validated")=ROWS(tblPolicies[Status]),"READY","BLOCKED")', f["bad"], "BLOCKED")
    setup.write(10, 0, "Operating rule", f["section"])
    setup.merge_range(11, 0, 13, 7,
                      "Scenario payout is visible for management discussion. Released payout remains blank until every policy is Validated, the employee is eligible, and Data Status is VALIDATED. The source workbook is never modified.",
                      f["note"])
    wb.define_name("Bonus_Report_Period", "=SETUP!$B$5")

    policy_ws = book.sheet("POLICY_APPROVAL", "Policy approval",
                           "Every row must be Validated before payroll release. Owners must document the approved choice.", 6)
    policy_ws.freeze_panes(4, 0)
    policy_ws.set_column("A:A", 28)
    policy_ws.set_column("B:B", 22)
    policy_ws.set_column("C:C", 35)
    policy_ws.set_column("D:D", 36)
    policy_ws.set_column("E:E", 22)
    policy_ws.set_column("F:F", 16)
    policy_ws.set_column("G:G", 30)
    policy_headers = ["Policy", "Selected Decision", "Allowed Values", "Formula Impact", "Owner", "Status", "Comments"]
    for col, header in enumerate(policy_headers):
        policy_ws.write(3, col, header, f["header"])
    for index, values in enumerate(policies, 4):
        padded = list(values[:7]) + [None] * (7 - len(values[:7]))
        for col, value in enumerate(padded[:7]):
            policy_ws.write(index, col, value, f["input"] if col in {1, 5, 6} else f["body"])
    policy_ws.add_table(3, 0, 3 + len(policies), 6, {
        "name": "tblPolicies", "style": "Table Style Light 9",
        "columns": [{"header": h, "header_format": f["header"]} for h in policy_headers],
    })
    policy_ws.data_validation(4, 5, 3 + len(policies), 5,
                              {"validate": "list", "source": ["To validate", "Validated", "Rejected"]})
    policy_ws.conditional_format(4, 5, 3 + len(policies), 5,
                                 {"type": "text", "criteria": "containing", "value": "Validated", "format": f["good"]})
    policy_ws.conditional_format(4, 5, 3 + len(policies), 5,
                                 {"type": "text", "criteria": "not containing", "value": "Validated", "format": f["bad"]})

    rules_ws = book.sheet("BONUS_RULES", "Central bonus rules",
                          "All thresholds and weights are visible here. Duplicate Population + KPI rows are blocked by controls.", 9)
    rules_headers = ["Population", "KPI", "Direction", "Tier 1 Bonus %", "Tier 1 Target", "Tier 2 Bonus %", "Tier 2 Target"]
    for col, header in enumerate(rules_headers):
        rules_ws.write(3, col, header, f["header"])
    for row_index, rule in enumerate(rules, 4):
        values = [rule.population, rule.kpi, rule.direction, rule.tier1_bonus, rule.tier1_target,
                  rule.tier2_bonus, rule.tier2_target]
        for col, value in enumerate(values):
            rules_ws.write(row_index, col, value, f["input"] if col >= 2 else f["body"])
    rules_ws.add_table(3, 0, 3 + len(rules), 6, {
        "name": "tblBonusRules", "style": "Table Style Light 9",
        "columns": [{"header": h, "header_format": f["header"]} for h in rules_headers],
    })
    rules_ws.set_column("A:A", 16)
    rules_ws.set_column("B:B", 28)
    rules_ws.set_column("C:C", 11)
    rules_ws.set_column("D:G", 18)
    rules_ws.write("I4", "VOC detractors", f["header"])
    rules_ws.write("J4", "Malus impact", f["header"])
    for index, (count, impact) in enumerate(((0, 0), (1, .1), (2, .2), (3, .5), (4, .75), (5, 1)), 4):
        rules_ws.write(index, 8, count, f["input"])
        rules_ws.write(index, 9, impact, f["input"])
    rules_ws.add_table(3, 8, 9, 9, {"name": "tblMalusRules", "style": "Table Style Light 9",
                                             "columns": [{"header": "VOC Detractors"}, {"header": "Malus Impact"}]})
    rules_ws.set_column("I:J", 18)

    input_ws = book.sheet("AGENT_INPUT", "Agent bonus input",
                          "Paste or type one agent-period per row. Blue cells are inputs; synthetic rows remain clearly labelled.", 19)
    input_ws.freeze_panes(4, 4)
    input_headers = ["Agent ID", "Agent Name", "Population", "Period", "AHT", "Productivity",
                     "PCS Score", "PCS Participation", "QM", "Absence %", "VOC Detractors", "Currency",
                     "Monthly Fixed Salary", "Target Bonus Rate", "Reference Bonus Override", "Eligible Days",
                     "Scheduled Days", "Employment Status", "Data Status", "Notes"]
    for col, header in enumerate(input_headers):
        input_ws.write(3, col, header, f["header"])
    normalized: list[list[Any]] = []
    for record in records:
        normalized.append([
            _bonus_value(record, "Agent ID"), _bonus_value(record, "Agent Name"), _bonus_value(record, "Population"),
            _bonus_value(record, "Period") or period, _bonus_value(record, "AHT"), _bonus_value(record, "Productivity"),
            _bonus_value(record, "PCS Score"), _bonus_value(record, "PCS % Participation", "PCS % (Participation)"),
            _bonus_value(record, "QM"), _bonus_value(record, "Abs%"), _bonus_value(record, "VOC Detractor Count"),
            _bonus_value(record, "Currency") or "MAD", _bonus_value(record, "Monthly Fixed Salary"),
            _bonus_value(record, "Target Bonus Rate"), _bonus_value(record, "Reference Bonus Override"),
            _bonus_value(record, "Eligible Days"), _bonus_value(record, "Scheduled Days"),
            _bonus_value(record, "Employment Status") or "Not supplied", _bonus_value(record, "Data Status"),
            _bonus_value(record, "Notes"),
        ])
    for position in range(capacity):
        row_index = position + 4
        values = normalized[position] if position < len(normalized) else [None] * len(input_headers)
        for col, value in enumerate(values):
            fmt = f["input"]
            if col in {7, 8, 9, 13}:
                fmt = f["pct"] if value is not None else f["input"]
            input_ws.write(row_index, col, value, fmt)
    input_ws.add_table(3, 0, 3 + capacity, len(input_headers) - 1, {
        "name": "tblBonusInput", "style": "Table Style Light 9",
        "columns": [{"header": h, "header_format": f["header"]} for h in input_headers],
    })
    input_ws.set_column("A:A", 14)
    input_ws.set_column("B:B", 25)
    input_ws.set_column("C:D", 15)
    input_ws.set_column("E:Q", 17)
    input_ws.set_column("R:S", 18)
    input_ws.set_column("T:T", 30)
    input_ws.data_validation(4, 2, 3 + capacity, 2, {"validate": "list", "source": sorted({r.population for r in rules})})
    input_ws.data_validation(4, 17, 3 + capacity, 17,
                             {"validate": "list", "source": ["Active", "Leaver", "Probation", "Excluded", "Not supplied"]})
    input_ws.data_validation(4, 18, 3 + capacity, 18,
                             {"validate": "list", "source": ["DRAFT", "VALIDATED", "SYNTHETIC", "REVIEW"]})

    calc = book.sheet("AGENT_RESULTS", "Agent calculation",
                      "Formula-driven scenario and released payout. Released payout cannot appear while a gate is blocked.", 20)
    calc.freeze_panes(4, 3)
    calc_headers = ["Agent ID", "Agent", "Population", "Core Input", "Eligibility Review", "AHT Earned",
                    "Productivity Earned", "PCS Earned", "Participation Earned", "QM Earned", "Absence Earned",
                    "Extra PCS Earned", "Gross Achievement", "VOC Malus", "Final Achievement", "Reference Bonus",
                    "Proration", "Scenario Payout", "Released Payout", "Release Status", "Data Issue"]
    for col, header in enumerate(calc_headers):
        calc.write(3, col, header, f["header"])
    rule_last = 4 + len(rules)
    rule_range = f"BONUS_RULES!$A$5:$A${rule_last}"
    kpi_range = f"BONUS_RULES!$B$5:$B${rule_last}"
    t1_bonus = f"BONUS_RULES!$D$5:$D${rule_last}"
    t1_target = f"BONUS_RULES!$E$5:$E${rule_last}"
    t2_bonus = f"BONUS_RULES!$F$5:$F${rule_last}"
    t2_target = f"BONUS_RULES!$G$5:$G${rule_last}"

    def score_formula(excel_row: int, actual_col: str, kpi: str, lower: bool = False) -> str:
        op = "<=" if lower else ">="
        return (f'=IF(OR($A{excel_row}="",$D{excel_row}<>"READY"),"",IF(AGENT_INPUT!{actual_col}{excel_row}{op}'
                f'SUMIFS({t1_target},{rule_range},$C{excel_row},{kpi_range},"{kpi}"),'
                f'SUMIFS({t1_bonus},{rule_range},$C{excel_row},{kpi_range},"{kpi}"),IF(AGENT_INPUT!{actual_col}{excel_row}{op}'
                f'SUMIFS({t2_target},{rule_range},$C{excel_row},{kpi_range},"{kpi}"),'
                f'SUMIFS({t2_bonus},{rule_range},$C{excel_row},{kpi_range},"{kpi}"),0)))')

    for position in range(capacity):
        row = position + 4
        erow = row + 1
        cached = results[position] if position < len(results) else BonusResult()
        record = normalized[position] if position < len(normalized) else [None] * len(input_headers)
        values: list[tuple[str, Any, str]] = [
            (f'=IF(AGENT_INPUT!A{erow}="","",AGENT_INPUT!A{erow})', record[0] or "", "body"),
            (f'=IF($A{erow}="","",AGENT_INPUT!B{erow})', record[1] or "", "body"),
            (f'=IF($A{erow}="","",AGENT_INPUT!C{erow})', record[2] or "", "body"),
            (f'=IF($A{erow}="","",IF(AND(COUNT(AGENT_INPUT!E{erow}:J{erow})=6,COUNT(AGENT_INPUT!K{erow})=1,COUNTIF({rule_range},AGENT_INPUT!C{erow})>0,OR(AGENT_INPUT!O{erow}>0,AND(AGENT_INPUT!M{erow}>0,AGENT_INPUT!N{erow}>0)),AGENT_INPUT!P{erow}>=0,AGENT_INPUT!Q{erow}>0,AGENT_INPUT!P{erow}<=AGENT_INPUT!Q{erow},AGENT_INPUT!H{erow}>=0,AGENT_INPUT!H{erow}<=1,AGENT_INPUT!I{erow}>=0,AGENT_INPUT!I{erow}<=1,AGENT_INPUT!J{erow}>=0,AGENT_INPUT!J{erow}<=1),"READY","BLOCKED"))', "READY" if cached.core_ready else "BLOCKED" if record[0] else "", "body"),
            (f'=IF($A{erow}="","",IF(AGENT_INPUT!R{erow}<>"Active","REVIEW",IF(OR(POLICY_APPROVAL!$B$9="Eligibility only",POLICY_APPROVAL!$B$9="Both"),IF(AGENT_INPUT!J{erow}<=SUMIFS({t1_target},{rule_range},$C{erow},{kpi_range},"Abs%"),"ELIGIBLE","INELIGIBLE ABS"),"ELIGIBLE")))', cached.eligibility, "body"),
        ]
        score_specs = [("E", "AHT", True), ("F", "Productivity", False), ("G", "PCS Score", False),
                       ("H", "PCS % (Participation)", False), ("I", "QM", False), ("J", "Abs%", True),
                       ("G", "Extra Bonus (PCS Score)", False)]
        earned_cached = list(cached.earned) + [None] * (7 - len(cached.earned))
        for index, (column, kpi, lower) in enumerate(score_specs):
            formula = score_formula(erow, column, kpi, lower)
            if kpi == "Abs%":
                formula = f'=IF(POLICY_APPROVAL!$B$9="Eligibility only",0,{formula[1:]})'
            values.append((formula, earned_cached[index] if earned_cached[index] is not None else "", "pct"))
        values.extend([
            (f'=IF($A{erow}="","",MIN(IF(POLICY_APPROVAL!$B$6="Replacement",SUM(F{erow}:K{erow})-H{erow}+MAX(H{erow},L{erow}),SUM(F{erow}:L{erow})),POLICY_APPROVAL!$B$10))', cached.gross or 0 if record[0] else "", "pct"),
            (f'=IF($A{erow}="","",IFERROR(INDEX(BONUS_RULES!$J$5:$J$10,MATCH(MIN(MAX(AGENT_INPUT!K{erow},0),5),BONUS_RULES!$I$5:$I$10,0)),1))', cached.malus or 0 if record[0] else "", "pct"),
            (f'=IF(M{erow}="","",MAX(0,IF(POLICY_APPROVAL!$B$5="Percentage points",M{erow}-N{erow},M{erow}*(1-N{erow}))))', cached.final or 0 if record[0] else "", "pct"),
            (f'=IF(D{erow}<>"READY","",IF(AGENT_INPUT!O{erow}>0,AGENT_INPUT!O{erow},AGENT_INPUT!M{erow}*AGENT_INPUT!N{erow}/IF(POLICY_APPROVAL!$B$7="Annual",12,1)))', cached.reference or "", "money"),
            (f'=IF(D{erow}<>"READY","",MIN(1,AGENT_INPUT!P{erow}/AGENT_INPUT!Q{erow}))', cached.proration or "", "pct"),
            (f'=IF(D{erow}<>"READY","",ROUND(P{erow}*Q{erow}*O{erow},IF(POLICY_APPROVAL!$B$11="Whole MAD",0,2)))', cached.scenario or "", "money"),
            (f'=IF(AND(SETUP!$B$9="READY",T{erow}="READY"),R{erow},"")', cached.release or "", "money"),
            (f'=IF($A{erow}="","",IF(D{erow}<>"READY","BLOCKED - INPUT",IF(E{erow}<>"ELIGIBLE","BLOCKED - ELIGIBILITY",IF(AGENT_INPUT!S{erow}<>"VALIDATED","BLOCKED - DATA",IF(SETUP!$B$9<>"READY","BLOCKED - POLICY","READY")))))', cached.status if record[0] else "", "body"),
            (f'=IF($A{erow}="","",IF(COUNTIFS(AGENT_INPUT!$A$5:$A${capacity+4},$A{erow},AGENT_INPUT!$D$5:$D${capacity+4},AGENT_INPUT!D{erow})>1,"DUPLICATE AGENT + PERIOD",IF(D{erow}<>"READY","INPUT OR CONFIG REVIEW",IF(T{erow}<>"READY",T{erow},""))))', cached.issue if record[0] else "", "body"),
        ])
        for col, (formula, value, fmt) in enumerate(values):
            calc.write_formula(row, col, formula, f[fmt], value)
    calc.add_table(3, 0, 3 + capacity, len(calc_headers) - 1, {
        "name": "tblBonusCalc", "style": "Table Style Light 9",
        "columns": [{"header": h, "header_format": f["header"]} for h in calc_headers],
    })
    calc.set_column("A:A", 14)
    calc.set_column("B:B", 24)
    calc.set_column("C:E", 19)
    calc.set_column("F:Q", 17)
    calc.set_column("R:S", 19)
    calc.set_column("T:U", 26)
    calc.conditional_format(4, 19, 3 + capacity, 19,
                            {"type": "text", "criteria": "containing", "value": "READY", "format": f["good"]})
    calc.conditional_format(4, 19, 3 + capacity, 19,
                            {"type": "text", "criteria": "containing", "value": "BLOCKED", "format": f["bad"]})

    scenario_total = sum(result.scenario or 0 for result in results)
    gross_total = sum((result.reference or 0) * (result.proration or 0) * (result.gross or 0) for result in results)
    malus_deduction = gross_total - scenario_total
    populations = sorted({rule.population for rule in rules})
    result_pairs = list(zip(records, results))
    total_agents = len(records)
    input_ready = sum(result.core_ready for result in results)
    paid_agents = sum((result.scenario or 0) > 0 for result in results)
    average_paid = scenario_total / paid_agents if paid_agents else 0
    highest_paid = max((result.scenario or 0 for result in results), default=0)
    pending_policies = sum(
        not (len(row) > 5 and _clean(row[5]).casefold() == "validated") for row in policies
    )
    eligibility_reviews = sum(result.eligibility == "REVIEW" for result in results)
    open_reviews = sum(result.status != "READY" for result in results) + pending_policies
    released_total = sum(result.release or 0 for result in results)
    release_state = "READY" if open_reviews == 0 else "BLOCKED"
    try:
        period_title = datetime.strptime(period, "%Y-%m").strftime("%B %Y").upper()
    except ValueError:
        period_title = period.upper()

    # The executive cockpit intentionally follows the stronger hierarchy of
    # the uploaded management dashboard: three primary cards, secondary status
    # chips, a complete LOB table, two comparison charts, payout distribution,
    # and a visible governance footer.
    management = wb.add_worksheet("MANAGEMENT")
    management.hide_gridlines(2)
    management.set_tab_color(COLORS["teal"])
    management.set_default_row(19.5)
    management.freeze_panes(10, 1)
    management.set_zoom(90)
    management.set_landscape()
    management.fit_to_pages(1, 2)
    management.print_area("B1:O62")
    management.set_column("A:A", 3)
    management.set_column("B:B", 18)
    management.set_column("C:D", 12)
    management.set_column("E:E", 14)
    management.set_column("F:F", 3)
    management.set_column("G:G", 18)
    management.set_column("H:I", 12)
    management.set_column("J:J", 14)
    management.set_column("K:K", 3)
    management.set_column("L:L", 18)
    management.set_column("M:N", 12)
    management.set_column("O:O", 14)
    management.set_column("P:P", 3)

    add = wb.add_format
    dash_title = add({"font_name": "Aptos Display", "font_size": 20, "bold": True,
                      "font_color": COLORS["white"], "bg_color": COLORS["navy"],
                      "valign": "vcenter", "indent": 1})
    dash_subtitle = add({"font_name": "Aptos", "font_size": 9, "font_color": "#C9D6E2",
                         "bg_color": COLORS["navy"], "valign": "vcenter", "indent": 1})
    dash_period = add({"font_name": "Aptos", "font_size": 9, "bold": True,
                       "font_color": COLORS["teal_light"], "bg_color": COLORS["navy"],
                       "align": "center", "valign": "vcenter"})
    dash_status = add({"font_name": "Aptos", "font_size": 9, "bold": True,
                       "font_color": COLORS["white"], "bg_color": COLORS["red"],
                       "align": "center", "valign": "vcenter"})
    card_label_teal = add({"font_name": "Aptos", "font_size": 10, "bold": True,
                           "font_color": COLORS["white"], "bg_color": COLORS["teal"],
                           "align": "center", "valign": "vcenter"})
    card_label_blue = add({"font_name": "Aptos", "font_size": 10, "bold": True,
                           "font_color": COLORS["white"], "bg_color": "#2F75B5",
                           "align": "center", "valign": "vcenter"})
    card_label_navy = add({"font_name": "Aptos", "font_size": 10, "bold": True,
                           "font_color": COLORS["white"], "bg_color": "#173F5F",
                           "align": "center", "valign": "vcenter"})
    card_money = add({"font_name": "Aptos Display", "font_size": 22, "bold": True,
                      "font_color": COLORS["navy"], "bg_color": COLORS["white"],
                      "num_format": '#,##0.00 "MAD"', "align": "center", "valign": "vcenter",
                      "border": 1, "border_color": COLORS["line"]})
    card_integer = add({"font_name": "Aptos Display", "font_size": 22, "bold": True,
                        "font_color": COLORS["navy"], "bg_color": COLORS["white"],
                        "num_format": "#,##0", "align": "center", "valign": "vcenter",
                        "border": 1, "border_color": COLORS["line"]})
    small_label = add({"font_name": "Aptos", "font_size": 8, "bold": True,
                       "font_color": COLORS["muted"], "align": "center", "valign": "vcenter"})
    chip_green = add({"font_name": "Aptos Display", "font_size": 12, "bold": True,
                      "font_color": COLORS["white"], "bg_color": COLORS["green"],
                      "num_format": "0.0%", "align": "center", "valign": "vcenter"})
    chip_gold = add({"font_name": "Aptos Display", "font_size": 12, "bold": True,
                     "font_color": COLORS["white"], "bg_color": COLORS["gold"],
                     "num_format": '#,##0.00 "MAD"', "align": "center", "valign": "vcenter"})
    chip_red = add({"font_name": "Aptos Display", "font_size": 12, "bold": True,
                    "font_color": COLORS["white"], "bg_color": COLORS["red"],
                    "num_format": "#,##0", "align": "center", "valign": "vcenter"})
    dash_section = add({"font_name": "Aptos", "font_size": 11, "bold": True,
                        "font_color": COLORS["white"], "bg_color": COLORS["navy"],
                        "valign": "vcenter", "indent": 1, "bottom": 2,
                        "bottom_color": COLORS["gold"]})
    table_header = add({"font_name": "Aptos", "font_size": 8, "bold": True,
                        "font_color": COLORS["white"], "bg_color": "#173F5F",
                        "align": "center", "valign": "vcenter", "text_wrap": True})
    row_name = add({"font_name": "Aptos", "font_size": 10, "bold": True,
                    "font_color": COLORS["navy"], "bg_color": COLORS["white"],
                    "bottom": 1, "bottom_color": COLORS["line"]})
    row_name_alt = add({"font_name": "Aptos", "font_size": 10, "bold": True,
                        "font_color": COLORS["navy"], "bg_color": COLORS["canvas"],
                        "bottom": 1, "bottom_color": COLORS["line"]})
    row_int = add({"font_name": "Aptos", "font_size": 10, "num_format": "#,##0",
                   "bg_color": COLORS["white"], "align": "center",
                   "bottom": 1, "bottom_color": COLORS["line"]})
    row_int_alt = add({"font_name": "Aptos", "font_size": 10, "num_format": "#,##0",
                       "bg_color": COLORS["canvas"], "align": "center",
                       "bottom": 1, "bottom_color": COLORS["line"]})
    row_pct = add({"font_name": "Aptos", "font_size": 10, "num_format": "0.0%",
                   "bg_color": COLORS["white"], "align": "center",
                   "bottom": 1, "bottom_color": COLORS["line"]})
    row_pct_alt = add({"font_name": "Aptos", "font_size": 10, "num_format": "0.0%",
                       "bg_color": COLORS["canvas"], "align": "center",
                       "bottom": 1, "bottom_color": COLORS["line"]})
    row_money = add({"font_name": "Aptos", "font_size": 10, "num_format": '#,##0.00 "MAD"',
                     "bg_color": COLORS["white"], "align": "right",
                     "bottom": 1, "bottom_color": COLORS["line"]})
    row_money_alt = add({"font_name": "Aptos", "font_size": 10, "num_format": '#,##0.00 "MAD"',
                         "bg_color": COLORS["canvas"], "align": "right",
                         "bottom": 1, "bottom_color": COLORS["line"]})
    total_label = add({"font_name": "Aptos", "font_size": 10, "bold": True,
                       "font_color": COLORS["navy"], "bg_color": "#EAF2F8",
                       "top": 2, "top_color": COLORS["teal"]})
    total_int = add({"font_name": "Aptos", "font_size": 10, "bold": True,
                     "font_color": COLORS["navy"], "bg_color": "#EAF2F8",
                     "num_format": "#,##0", "align": "center", "top": 2,
                     "top_color": COLORS["teal"]})
    total_pct = add({"font_name": "Aptos", "font_size": 10, "bold": True,
                     "font_color": COLORS["navy"], "bg_color": "#EAF2F8",
                     "num_format": "0.0%", "align": "center", "top": 2,
                     "top_color": COLORS["teal"]})
    total_money = add({"font_name": "Aptos", "font_size": 10, "bold": True,
                       "font_color": COLORS["navy"], "bg_color": "#EAF2F8",
                       "num_format": '#,##0.00 "MAD"', "align": "right", "top": 2,
                       "top_color": COLORS["teal"]})
    governance_value = add({"font_name": "Aptos Display", "font_size": 19, "bold": True,
                            "font_color": COLORS["navy"], "bg_color": COLORS["white"],
                            "align": "center", "valign": "vcenter", "border": 1,
                            "border_color": COLORS["line"]})

    management.merge_range("B1:O1", f"{period_title}  |  BONUS PAYOUT COCKPIT", dash_title)
    management.merge_range("B2:I2", "MANAGEMENT VIEW  /  PAYOUT, COVERAGE AND RELEASE CONTROL", dash_subtitle)
    management.merge_range("J2:L2", f"PERIOD  |  {period}", dash_period)
    management.merge_range("M2:O2", f"PAYROLL  |  {release_state}", dash_status if release_state == "BLOCKED" else f["good"])

    def dashboard_card(label_range: str, value_range: str, label: str, formula: str,
                       cached: Any, label_format, value_format) -> None:
        management.merge_range(label_range, label, label_format)
        management.merge_range(value_range, "", value_format)
        management.write_formula(value_range.split(":")[0], formula, value_format, cached)

    dashboard_card("B4:D4", "B5:D7", "SCENARIO PAYOUT", '=SUM(tblBonusCalc[Scenario Payout])',
                   scenario_total, card_label_teal, card_money)
    dashboard_card("G4:I4", "G5:I7", "AGENTS WITH PAYOUT", '=COUNTIF(tblBonusCalc[Scenario Payout],">0")',
                   paid_agents, card_label_blue, card_integer)
    dashboard_card("L4:N4", "L5:N7", "AVERAGE PAID PAYOUT", '=IFERROR(AVERAGEIF(tblBonusCalc[Scenario Payout],">0"),0)',
                   average_paid, card_label_navy, card_money)
    management.merge_range("B8:D8", "INPUT READINESS", small_label)
    management.merge_range("G8:I8", "HIGHEST SCENARIO PAYOUT", small_label)
    management.merge_range("L8:N8", "OPEN RELEASE REVIEWS", small_label)
    management.merge_range("B9:D9", "", chip_green)
    management.write_formula("B9", '=IFERROR(COUNTIF(tblBonusCalc[Core Input],"READY")/COUNTIF(tblBonusCalc[Agent ID],"<>"),0)', chip_green,
                             input_ready / total_agents if total_agents else 0)
    management.merge_range("G9:I9", "", chip_gold)
    management.write_formula("G9", '=MAX(tblBonusCalc[Scenario Payout])', chip_gold, highest_paid)
    management.merge_range("L9:N9", "", chip_red)
    management.write_formula("L9", '=COUNTIFS(tblBonusCalc[Agent ID],"<>",tblBonusCalc[Release Status],"<>READY")+COUNTIF(tblPolicies[Status],"<>Validated")',
                             chip_red, open_reviews)

    management.merge_range("B11:O11", "LOB DECOMPOSITION  |  SCALE, INPUT COVERAGE AND PAYOUT EXPOSURE", dash_section)
    lob_headers = ["LOB", "Agents", "Input Ready", "Input Blocked", "Ready Rate", "Paid Agents",
                   "Scenario Payout", "Share of Total", "Average Paid"]
    for col, header in enumerate(lob_headers, 1):
        management.write(12, col, header, table_header)
    population_cache: list[dict[str, Any]] = []
    for position, population in enumerate(populations):
        row = 13 + position
        excel_row = row + 1
        population_results = [result for record, result in result_pairs
                              if _clean(_bonus_value(record, "Population")) == population]
        pop_agents = len(population_results)
        pop_ready = sum(result.core_ready for result in population_results)
        pop_paid = sum((result.scenario or 0) > 0 for result in population_results)
        pop_payout = sum(result.scenario or 0 for result in population_results)
        population_cache.append({"agents": pop_agents, "ready": pop_ready, "paid": pop_paid, "payout": pop_payout})
        alternating = position % 2 == 1
        name_fmt = row_name_alt if alternating else row_name
        int_fmt = row_int_alt if alternating else row_int
        pct_fmt = row_pct_alt if alternating else row_pct
        money_fmt = row_money_alt if alternating else row_money
        management.write(row, 1, population, name_fmt)
        management.write_formula(row, 2, f'=COUNTIF(tblBonusCalc[Population],$B{excel_row})', int_fmt, pop_agents)
        management.write_formula(row, 3, f'=COUNTIFS(tblBonusCalc[Population],$B{excel_row},tblBonusCalc[Core Input],"READY")', int_fmt, pop_ready)
        management.write_formula(row, 4, f'=C{excel_row}-D{excel_row}', int_fmt, pop_agents - pop_ready)
        management.write_formula(row, 5, f'=IFERROR(D{excel_row}/C{excel_row},0)', pct_fmt, pop_ready / pop_agents if pop_agents else 0)
        management.write_formula(row, 6, f'=COUNTIFS(tblBonusCalc[Population],$B{excel_row},tblBonusCalc[Scenario Payout],">0")', int_fmt, pop_paid)
        management.write_formula(row, 7, f'=SUMIF(tblBonusCalc[Population],$B{excel_row},tblBonusCalc[Scenario Payout])', money_fmt, pop_payout)
        management.write_formula(row, 8, f'=IFERROR(H{excel_row}/SUM($H$14:$H${13+len(populations)}),0)', pct_fmt,
                                 pop_payout / scenario_total if scenario_total else 0)
        management.write_formula(row, 9, f'=IFERROR(H{excel_row}/G{excel_row},0)', money_fmt,
                                 pop_payout / pop_paid if pop_paid else 0)
    total_row = 13 + len(populations)
    total_excel = total_row + 1
    management.write(total_row, 1, "TOTAL / ALL", total_label)
    management.write_formula(total_row, 2, '=COUNTIF(tblBonusCalc[Agent ID],"<>")', total_int, total_agents)
    management.write_formula(total_row, 3, '=COUNTIF(tblBonusCalc[Core Input],"READY")', total_int, input_ready)
    management.write_formula(total_row, 4, f'=C{total_excel}-D{total_excel}', total_int, total_agents - input_ready)
    management.write_formula(total_row, 5, f'=IFERROR(D{total_excel}/C{total_excel},0)', total_pct,
                             input_ready / total_agents if total_agents else 0)
    management.write_formula(total_row, 6, '=COUNTIF(tblBonusCalc[Scenario Payout],">0")', total_int, paid_agents)
    management.write_formula(total_row, 7, '=SUM(tblBonusCalc[Scenario Payout])', total_money, scenario_total)
    management.write_formula(total_row, 8, '=IFERROR(H{0}/H{0},0)'.format(total_excel), total_pct, 1 if scenario_total else 0)
    management.write_formula(total_row, 9, f'=IFERROR(H{total_excel}/G{total_excel},0)', total_money, average_paid)

    management.merge_range("B22:O22", "MANAGEMENT VISUALS  |  PAYOUT MIX AND INPUT COVERAGE", dash_section)
    payout_chart = wb.add_chart({"type": "column"})
    payout_chart.add_series({"name": "Scenario payout", "categories": ["MANAGEMENT", 13, 1, 12 + len(populations), 1],
                             "values": ["MANAGEMENT", 13, 7, 12 + len(populations), 7],
                             "fill": {"color": COLORS["teal"]}, "border": {"none": True}})
    payout_chart.set_title({"name": "Scenario payout by LOB"})
    payout_chart.set_legend({"none": True})
    payout_chart.set_y_axis({"num_format": '#,##0 "MAD"', "major_gridlines": {"visible": False}})
    payout_chart.set_chartarea({"border": {"none": True}, "fill": {"color": COLORS["white"]}})
    payout_chart.set_plotarea({"border": {"none": True}, "fill": {"color": COLORS["white"]}})
    management.insert_chart("B24", payout_chart, {"x_scale": 1.20, "y_scale": 1.08})

    readiness_chart = wb.add_chart({"type": "column", "subtype": "stacked"})
    readiness_chart.add_series({"name": "Input ready", "categories": ["MANAGEMENT", 13, 1, 12 + len(populations), 1],
                                "values": ["MANAGEMENT", 13, 3, 12 + len(populations), 3],
                                "fill": {"color": COLORS["green"]}, "border": {"none": True}})
    readiness_chart.add_series({"name": "Input blocked", "categories": ["MANAGEMENT", 13, 1, 12 + len(populations), 1],
                                "values": ["MANAGEMENT", 13, 4, 12 + len(populations), 4],
                                "fill": {"color": COLORS["red"]}, "border": {"none": True}})
    readiness_chart.set_title({"name": "Input-ready versus blocked agents"})
    readiness_chart.set_legend({"position": "bottom"})
    readiness_chart.set_y_axis({"major_unit": 10, "major_gridlines": {"visible": False}})
    readiness_chart.set_chartarea({"border": {"none": True}, "fill": {"color": COLORS["white"]}})
    readiness_chart.set_plotarea({"border": {"none": True}, "fill": {"color": COLORS["white"]}})
    management.insert_chart("I24", readiness_chart, {"x_scale": 1.20, "y_scale": 1.08})

    management.merge_range("B40:O40", "PAYOUT DISTRIBUTION  |  AGENT CONCENTRATION", dash_section)
    distribution = [
        ("Input not ready", sum(not r.core_ready for r in results), '=COUNTIF(tblBonusCalc[Core Input],"BLOCKED")'),
        ("Ready / no payout", sum(r.core_ready and not (r.scenario or 0) for r in results), '=COUNTIFS(tblBonusCalc[Core Input],"READY",tblBonusCalc[Scenario Payout],0)'),
        ("1 - 499 MAD", sum(r.core_ready and 0 < (r.scenario or 0) < 500 for r in results), '=COUNTIFS(tblBonusCalc[Core Input],"READY",tblBonusCalc[Scenario Payout],">0",tblBonusCalc[Scenario Payout],"<500")'),
        ("500 - 999 MAD", sum(r.core_ready and 500 <= (r.scenario or 0) < 1000 for r in results), '=COUNTIFS(tblBonusCalc[Core Input],"READY",tblBonusCalc[Scenario Payout],">=500",tblBonusCalc[Scenario Payout],"<1000")'),
        ("1,000 - 1,499 MAD", sum(r.core_ready and 1000 <= (r.scenario or 0) < 1500 for r in results), '=COUNTIFS(tblBonusCalc[Core Input],"READY",tblBonusCalc[Scenario Payout],">=1000",tblBonusCalc[Scenario Payout],"<1500")'),
        ("1,500+ MAD", sum(r.core_ready and (r.scenario or 0) >= 1500 for r in results), '=COUNTIFS(tblBonusCalc[Core Input],"READY",tblBonusCalc[Scenario Payout],">=1500")'),
    ]
    for col, header in enumerate(("Payout band", "Agents", "Share"), 1):
        management.write(41, col, header, table_header)
    for position, (label, count, formula) in enumerate(distribution):
        row, excel_row = 42 + position, 43 + position
        alternating = position % 2 == 1
        management.write(row, 1, label, row_name_alt if alternating else row_name)
        management.write_formula(row, 2, formula, row_int_alt if alternating else row_int, count)
        management.write_formula(row, 3, f'=IFERROR(C{excel_row}/SUM($C$43:$C$48),0)',
                                 row_pct_alt if alternating else row_pct, count / total_agents if total_agents else 0)
    distribution_chart = wb.add_chart({"type": "doughnut"})
    distribution_chart.add_series({"name": "Agent payout distribution",
                                   "categories": ["MANAGEMENT", 42, 1, 47, 1],
                                   "values": ["MANAGEMENT", 42, 2, 47, 2],
                                   "points": [
                                       {"fill": {"color": COLORS["red"]}},
                                       {"fill": {"color": COLORS["muted"]}},
                                       {"fill": {"color": COLORS["amber"]}},
                                       {"fill": {"color": COLORS["gold"]}},
                                       {"fill": {"color": "#2F75B5"}},
                                       {"fill": {"color": COLORS["teal"]}},
                                   ]})
    distribution_chart.set_title({"name": "Agent payout distribution"})
    distribution_chart.set_hole_size(58)
    distribution_chart.set_legend({"position": "right"})
    distribution_chart.set_chartarea({"border": {"none": True}, "fill": {"color": COLORS["white"]}})
    management.insert_chart("F42", distribution_chart, {"x_scale": 1.20, "y_scale": 1.02})

    management.merge_range("B54:O54", "RELEASE GOVERNANCE  |  WHAT MANAGEMENT MUST APPROVE", dash_section)
    management.merge_range("B56:D56", "POLICIES VALIDATED", card_label_teal)
    management.merge_range("B57:D59", "", governance_value)
    management.write_formula("B57", '=COUNTIF(tblPolicies[Status],"Validated")&" / "&ROWS(tblPolicies[Status])', governance_value,
                             f"{len(policies)-pending_policies} / {len(policies)}")
    management.merge_range("G56:I56", "INPUT READY", card_label_blue)
    management.merge_range("G57:I59", "", governance_value)
    management.write_formula("G57", '=COUNTIF(tblBonusCalc[Core Input],"READY")&" / "&COUNTIF(tblBonusCalc[Agent ID],"<>")', governance_value,
                             f"{input_ready} / {total_agents}")
    management.merge_range("L56:N56", "PAYROLL RELEASE", card_label_navy)
    management.merge_range("L57:N59", "", governance_value)
    management.write_formula("L57", '=IF(AND(SETUP!$B$9="READY",COUNTIFS(tblBonusCalc[Agent ID],"<>",tblBonusCalc[Release Status],"<>READY")=0),"READY","BLOCKED")',
                             governance_value, release_state)
    management.merge_range("B61:O62",
                           f"Management scenario: {scenario_total:,.2f} MAD. Gross-before-malus exposure: {gross_total:,.2f} MAD; modeled malus impact: {malus_deduction:,.2f} MAD. Released payout is {released_total:,.2f} MAD until all policy, input, data-status and eligibility checks pass. Review POLICY_APPROVAL and CONTROLS before payroll use.",
                           f["note"])

    controls = book.sheet("CONTROLS", "Release controls",
                          "Resolve every BLOCKED control before treating any payout as operational.", 7)
    control_rows = [
        ("Policies validated", '=IF(SETUP!$B$9="READY","PASS","BLOCKED")', "BLOCKED"),
        ("Validated input rows", '=COUNTIFS(tblBonusInput[Agent ID],"<>",tblBonusInput[Data Status],"VALIDATED")', 0),
        ("Synthetic rows", '=COUNTIFS(tblBonusInput[Agent ID],"<>",tblBonusInput[Data Status],"SYNTHETIC")', sum(1 for row in normalized if _clean(row[18]) == "SYNTHETIC")),
        ("Blocked core input", '=COUNTIF(tblBonusCalc[Core Input],"BLOCKED")', sum(1 for r in results if not r.core_ready)),
        ("Eligibility review", '=COUNTIF(tblBonusCalc[Eligibility Review],"REVIEW")', sum(1 for r in results if r.eligibility == "REVIEW")),
        ("Duplicate agent-period rows", '=COUNTIF(tblBonusCalc[Data Issue],"DUPLICATE*")', 0),
        ("Released payout", '=SUM(tblBonusCalc[Released Payout])', 0),
    ]
    controls.write("A4", "Control", f["header"])
    controls.write("B4", "Result", f["header"])
    for index, (label, formula, cached_value) in enumerate(control_rows, 4):
        controls.write(index, 0, label, f["body"])
        controls.write_formula(index, 1, formula, f["body"], cached_value)
    controls.set_column("A:A", 36)
    controls.set_column("B:B", 22)

    logic = book.sheet("FORMULA_LOGIC", "Bonus formula logic",
                       "Plain-language definitions and the exact workbook implementation contract.", 7)
    logic_rows = [
        ("Core input gate", "All six KPIs, VOC, population config, bonus basis, and valid proration days must be present."),
        ("KPI award", "Lower-is-better: actual <= target. Higher-is-better: actual >= target. Tier 1 is evaluated before Tier 2."),
        ("Extra PCS", "Additive sums the extra PCS award; Replacement substitutes the higher of standard PCS and extra PCS."),
        ("Gross achievement", "Sum of earned KPI weights after absence treatment, then capped by Achievement cap."),
        ("VOC malus", "0/1/2/3/4/5+ detractors map to 0%/10%/20%/50%/75%/100%."),
        ("Final achievement", "Proportional: Gross × (1 − malus). Percentage points: MAX(0, Gross − malus)."),
        ("Reference bonus", "Override when positive; otherwise monthly salary × target rate, divided by 12 only when rate basis is Annual."),
        ("Proration", "MIN(1, Eligible Days ÷ Scheduled Days). Scheduled Days must follow the selected denominator policy."),
        ("Scenario payout", "Reference bonus × proration × final achievement, rounded per policy."),
        ("Released payout", "Scenario payout only when every policy is Validated, data is VALIDATED, core input is ready, and eligibility passes."),
    ]
    logic.write("A4", "Calculation", f["header"])
    logic.write("B4", "Definition", f["header"])
    for index, (label, definition) in enumerate(logic_rows, 4):
        logic.write(index, 0, label, f["body"])
        logic.write(index, 1, definition, f["note"])
        logic.set_row(index, 34)
    logic.set_column("A:A", 24)
    logic.set_column("B:B", 95)

    email = book.sheet("EMAIL_BRIEF", "Management email brief",
                       "Copy the subject and body below into your email; keep the governance warning.", 7)
    email.set_column("A:A", 18)
    email.set_column("B:H", 18)
    email.write("A4", "Subject", f["header"])
    email.merge_range("B4:H4", f"Bonus management proposal | {period} | policy validation required", f["input"])
    email.write("A6", "Body", f["header"])
    body = (
        f"Hello,\n\nPlease find attached the WFM bonus management proposal for {period}. "
        f"It models {len(records)} illustrative agent records and a scenario payout of {scenario_total:,.2f} MAD. "
        "The model centralizes KPI thresholds, VOC malus, proration, eligibility, and approval controls. "
        "It is intentionally blocked for payroll until all policy owners validate their decisions and operational data replaces synthetic records.\n\n"
        "The MANAGEMENT sheet provides the executive view; POLICY_APPROVAL and CONTROLS show the decisions required for release.\n\nRegards,\nAnass ASSRI"
    )
    email.merge_range("B6:H18", body, f["note"])
    email.set_row(5, 32)
    for row in range(6, 19):
        email.set_row(row, 21)

    for ws in (setup, policy_ws, rules_ws, input_ws, calc, management, controls, logic, email):
        ws.set_landscape()
        ws.fit_to_pages(1, 0)
        ws.set_footer("&LWFMHub | made by Anass ASSRI&CPage &P of &N&RConfidential")
    management.activate()
    management.select()
    return book.close()


def _read_pcs_roster(source: Path | None) -> tuple[list[list[Any]], date | None]:
    if source is None:
        return [], None
    if not source.exists():
        raise FileNotFoundError(source)
    workbook = load_workbook(source, read_only=True, data_only=True, keep_links=False)
    try:
        if "AGENT LIST" not in workbook.sheetnames:
            raise ValueError("PCS source must contain an AGENT LIST sheet")
        ws = workbook["AGENT LIST"]
        header_row = _header_row(ws, "Client ID", 10)
        headers = [_clean(ws.cell(header_row, col).value) for col in range(1, min(ws.max_column, 20) + 1)]
        index = {header.casefold(): position for position, header in enumerate(headers)}

        def pick(values: tuple[Any, ...], name: str) -> Any:
            position = index.get(name.casefold())
            return values[position] if position is not None and position < len(values) else None

        roster = []
        seen = set()
        for values in ws.iter_rows(min_row=header_row + 1, values_only=True):
            agent_id = pick(values, "Client ID")
            if agent_id in (None, ""):
                continue
            key = _clean(agent_id)
            if key in seen:
                continue
            seen.add(key)
            roster.append([agent_id, pick(values, "Status"), pick(values, "Name"),
                           pick(values, "Team leader"), pick(values, "Ops Manager"), pick(values, "LOB")])
        selected = None
        if "OverView" in workbook.sheetnames:
            value = workbook["OverView"]["B9"].value
            if isinstance(value, datetime):
                selected = value.date()
            elif isinstance(value, date):
                selected = value
        return roster, selected
    finally:
        workbook.close()


def _count_formula(start_ref: str, end_ref: str, extra: str = "") -> str:
    return (f'COUNTIFS(tblPCSInput[Call Date/Time],">="&({start_ref}),tblPCSInput[Call Date/Time],"<"&({end_ref}),'
            f'tblPCSInput[Call Direction],"I"{extra})')


def build_pcs_management(source: Path | None, output: Path, report_date: date | None = None) -> Path:
    """Build a paste-ready three-hour PCS template from the original workbook roster."""

    roster, original_date = _read_pcs_roster(source)
    report_date = report_date or original_date or date.today()
    roster_capacity = max(300, len(roster) + 25)
    window_start = datetime.combine(report_date, time(9, 0))
    window_end = datetime.combine(report_date, time(12, 0))
    book = ManagementBook(output, "PCS Management 3-Hour Report")
    wb, f = book.workbook, book.fmt

    setup = book.sheet("SETUP", "PCS management setup",
                       "Change the blue date/window cells before each management send.", 7)
    setup.set_column("A:A", 30)
    setup.set_column("B:B", 24)
    setup.set_column("C:H", 16)
    setup.write("A4", "Control", f["header"])
    setup.write("B4", "Value", f["header"])
    controls = [
        ("Report date", report_date, "input_date"),
        ("3-hour window start", window_start, "input_datetime"),
        ("3-hour window end", window_end, "input_datetime"),
        ("Prepared by", "Anass ASSRI", "input"),
        ("Generated at", datetime.now(), "datetime"),
    ]
    for index, (label, value, fmt) in enumerate(controls, 4):
        setup.write(index, 0, label, f["body"])
        setup.write(index, 1, value, f[fmt])
    setup.write(10, 0, "Data through", f["body"])
    setup.write_formula(10, 1, '=IFERROR(MAX(tblPCSInput[Call Date/Time]),"")', f["datetime"], "")
    setup.write(12, 0, "How to refresh", f["section"])
    setup.merge_range("A14:H18",
                      "1. Clear only the blue source columns in INPUT_CALLS.  2. Paste the required Call-by-Call fields under matching headers.  3. Update Report date and the three-hour window.  4. Review DATA_QUALITY.  5. Copy EMAIL_BRIEF and send the workbook. Every input row is one call leg; transferred calls can create multiple legs.",
                      f["note"])
    wb.define_name("PCS_Report_Date", "=SETUP!$B$5")
    wb.define_name("PCS_Window_Start", "=SETUP!$B$6")
    wb.define_name("PCS_Window_End", "=SETUP!$B$7")

    roster_ws = book.sheet("ROSTER", "PCS roster",
                           "Paste the current FTE roster here. Agent ID is the Storm/Verint Client ID.", 5)
    roster_ws.freeze_panes(4, 0)
    roster_headers = ["Agent ID", "Status", "Agent", "Team Leader", "Ops Manager", "LOB"]
    for col, header in enumerate(roster_headers):
        roster_ws.write(3, col, header, f["header"])
    for position in range(roster_capacity):
        values = roster[position] if position < len(roster) else [None] * len(roster_headers)
        for col, value in enumerate(values):
            roster_ws.write(position + 4, col, value, f["input"])
    roster_ws.add_table(3, 0, 3 + roster_capacity, 5, {
        "name": "tblPCSRoster", "style": "Table Style Light 9",
        "columns": [{"header": h, "header_format": f["header"]} for h in roster_headers],
    })
    roster_ws.set_column("A:B", 16)
    roster_ws.set_column("C:E", 24)
    roster_ws.set_column("F:F", 18)

    input_ws = book.sheet("INPUT_CALLS", "Call-by-Call input",
                          "Paste source values only in blue columns. Formula columns match roster and validate Question 1.", 19)
    input_ws.freeze_panes(4, 5)
    input_headers = ["Call Date/Time", "Call End Date/Time", "Call ID", "Call Direction", "Agent ID", "Agent",
                     "Talk Time", "Hold Time", "Total Wrap Time", "Language", "Queue", "PostCallSurveyMode",
                     "PCSStatus", "Question 1", "Team Leader", "Ops Manager", "LOB", "Valid Q1", "Q1 Nonblank", "Data Issue"]
    formula_columns = {
        "Team Leader": '=IF([@[Call Date/Time]]="","",IFERROR(INDEX(tblPCSRoster[Team Leader],MATCH([@[Agent ID]],tblPCSRoster[Agent ID],0)),""))',
        "Ops Manager": '=IF([@[Call Date/Time]]="","",IFERROR(INDEX(tblPCSRoster[Ops Manager],MATCH([@[Agent ID]],tblPCSRoster[Agent ID],0)),""))',
        "LOB": '=IF([@[Call Date/Time]]="","",IFERROR(INDEX(tblPCSRoster[LOB],MATCH([@[Agent ID]],tblPCSRoster[Agent ID],0)),""))',
        "Valid Q1": '=IF([@[Call Date/Time]]="","",IF(AND(ISNUMBER([@[Question 1]]),[@[Question 1]]>=1,[@[Question 1]]<=5,MOD([@[Question 1]],1)=0),[@[Question 1]],""))',
        "Q1 Nonblank": '=IF([@[Call Date/Time]]="","",--([@[Question 1]]<>""))',
        "Data Issue": '=IF([@[Call Date/Time]]="","",IF([@[Agent ID]]="","MISSING AGENT ID",IF(COUNTIF(tblPCSRoster[Agent ID],[@[Agent ID]])=0,"UNMATCHED AGENT",IF(AND([@[Question 1]]<>"",[@[Valid Q1]]=""),"INVALID Q1",""))))',
    }
    for col, header in enumerate(input_headers):
        input_ws.write(3, col, header, f["header"])
    # A one-row Excel Table expands automatically when the user pastes more rows.
    for col, header in enumerate(input_headers):
        if header in formula_columns:
            input_ws.write_formula(4, col, formula_columns[header], f["body"], "")
        else:
            input_ws.write_blank(4, col, None, f["input_datetime"] if col in {0, 1} else f["input"])
    table_columns = []
    for header in input_headers:
        definition: dict[str, Any] = {"header": header, "header_format": f["header"]}
        if header in formula_columns:
            definition["formula"] = formula_columns[header]
        table_columns.append(definition)
    input_ws.add_table(3, 0, 4, len(input_headers) - 1, {
        "name": "tblPCSInput", "style": "Table Style Light 9", "columns": table_columns,
    })
    input_ws.set_column("A:B", 20)
    input_ws.set_column("C:C", 19)
    input_ws.set_column("D:E", 15)
    input_ws.set_column("F:F", 24)
    input_ws.set_column("G:I", 16)
    input_ws.set_column("J:Q", 20)
    input_ws.set_column("R:T", 17)
    input_ws.data_validation(4, 3, 1048575, 3, {"validate": "list", "source": ["I", "O"]})

    details = book.sheet("AGENT_DETAIL", "PCS agent detail",
                         "Original O/P/Q/R logic, plus valid-response diagnostics and the selected three-hour interval.", 22)
    details.freeze_panes(4, 5)
    detail_headers = ["Agent ID", "Agent", "Team Leader", "Ops Manager", "LOB", "Eligible Calls Day", "Q1 Nonblank Day",
                      "Valid Q1 Day", "PCS Average Day", "<=3 Day", ">3 Day", "PCS Participation Day", "Valid Response Day",
                      "Invalid Q1 Day", "Sample Flag", "Eligible Calls 3H", "Q1 Nonblank 3H", "Valid Q1 3H", "PCS Average 3H",
                      "<=3 3H", ">3 3H", "PCS Participation 3H", "Valid Response 3H"]
    for col, header in enumerate(detail_headers):
        details.write(3, col, header, f["header"])

    def count_agent(erow: int, start: str, end: str, extra: str = "") -> str:
        return _count_formula(start, end, f',tblPCSInput[Agent ID],$A{erow}{extra}')

    for position in range(roster_capacity):
        row = position + 4
        erow = row + 1
        roster_values = roster[position] if position < len(roster) else [None] * 6
        agent_id = roster_values[0] or ""
        formulas: list[tuple[str, Any, str]] = [
            (f'=IF(ROSTER!A{erow}="","",ROSTER!A{erow})', agent_id, "body"),
            (f'=IF($A{erow}="","",ROSTER!C{erow})', roster_values[2] or "", "body"),
            (f'=IF($A{erow}="","",ROSTER!D{erow})', roster_values[3] or "", "body"),
            (f'=IF($A{erow}="","",ROSTER!E{erow})', roster_values[4] or "", "body"),
            (f'=IF($A{erow}="","",ROSTER!F{erow})', roster_values[5] or "", "body"),
        ]
        day_start, day_end = "SETUP!$B$5", "SETUP!$B$5+1"
        win_start, win_end = "SETUP!$B$6", "SETUP!$B$7"
        day_eligible = count_agent(erow, day_start, day_end, ',tblPCSInput[PCSStatus],1')
        day_nonblank = count_agent(erow, day_start, day_end, ',tblPCSInput[Question 1],"<>"')
        day_valid = count_agent(erow, day_start, day_end, ',tblPCSInput[Valid Q1],">=1"')
        day_low = count_agent(erow, day_start, day_end, ',tblPCSInput[Valid Q1],"<=3",tblPCSInput[Valid Q1],">=1"')
        day_high = count_agent(erow, day_start, day_end, ',tblPCSInput[Valid Q1],">3"')
        day_sum = (f'SUMIFS(tblPCSInput[Valid Q1],tblPCSInput[Call Date/Time],">="&{day_start},'
                   f'tblPCSInput[Call Date/Time],"<"&{day_end},tblPCSInput[Call Direction],"I",tblPCSInput[Agent ID],$A{erow})')
        win_eligible = count_agent(erow, win_start, win_end, ',tblPCSInput[PCSStatus],1')
        win_nonblank = count_agent(erow, win_start, win_end, ',tblPCSInput[Question 1],"<>"')
        win_valid = count_agent(erow, win_start, win_end, ',tblPCSInput[Valid Q1],">=1"')
        win_low = count_agent(erow, win_start, win_end, ',tblPCSInput[Valid Q1],"<=3",tblPCSInput[Valid Q1],">=1"')
        win_high = count_agent(erow, win_start, win_end, ',tblPCSInput[Valid Q1],">3"')
        win_sum = (f'SUMIFS(tblPCSInput[Valid Q1],tblPCSInput[Call Date/Time],">="&{win_start},'
                   f'tblPCSInput[Call Date/Time],"<"&{win_end},tblPCSInput[Call Direction],"I",tblPCSInput[Agent ID],$A{erow})')
        formulas.extend([
            (f'=IF($A{erow}="","",{day_eligible})', "", "int"),
            (f'=IF($A{erow}="","",{day_nonblank})', "", "int"),
            (f'=IF($A{erow}="","",{day_valid})', "", "int"),
            (f'=IFERROR({day_sum}/{day_valid},"")', "", "dec"),
            (f'=IF(I{erow}="","",{day_low})', "", "int"),
            (f'=IF(I{erow}="","",{day_high})', "", "int"),
            (f'=IFERROR(G{erow}/F{erow},"")', "", "pct"),
            (f'=IFERROR(H{erow}/F{erow},"")', "", "pct"),
            (f'=IF($A{erow}="","",MAX(0,G{erow}-H{erow}))', "", "int"),
            (f'=IF($A{erow}="","",IF(H{erow}=0,"NO VALID SURVEY",IF(H{erow}<5,"LOW SAMPLE","OK")))', "", "body"),
            (f'=IF($A{erow}="","",{win_eligible})', "", "int"),
            (f'=IF($A{erow}="","",{win_nonblank})', "", "int"),
            (f'=IF($A{erow}="","",{win_valid})', "", "int"),
            (f'=IFERROR({win_sum}/{win_valid},"")', "", "dec"),
            (f'=IF(S{erow}="","",{win_low})', "", "int"),
            (f'=IF(S{erow}="","",{win_high})', "", "int"),
            (f'=IFERROR(Q{erow}/P{erow},"")', "", "pct"),
            (f'=IFERROR(R{erow}/P{erow},"")', "", "pct"),
        ])
        for col, (formula, value, fmt) in enumerate(formulas):
            details.write_formula(row, col, formula, f[fmt], value)
    details.add_table(3, 0, 3 + roster_capacity, len(detail_headers) - 1, {
        "name": "tblPCSAgent", "style": "Table Style Light 9",
        "columns": [{"header": h, "header_format": f["header"]} for h in detail_headers],
    })
    details.set_column("A:A", 15)
    details.set_column("B:E", 23)
    details.set_column("F:W", 18)
    details.conditional_format(4, 14, 3 + roster_capacity, 14,
                               {"type": "text", "criteria": "containing", "value": "LOW", "format": f["warn"]})

    lobs = sorted({_clean(row[5]) for row in roster if _clean(row[5])})
    lob_capacity = max(15, len(lobs) + 5)
    lob_ws = book.sheet("LOB_SUMMARY", "PCS by LOB",
                        "Ratios are calculated from summed counters; agent averages are never averaged together.", 14)
    lob_headers = ["LOB", "Eligible Calls Day", "Q1 Nonblank Day", "Valid Q1 Day", "PCS Average Day", "<=3 Day", ">3 Day",
                   "PCS Participation Day", "Valid Response Day", "Eligible Calls 3H", "Valid Q1 3H", "PCS Average 3H",
                   "PCS Participation 3H", "Valid Response 3H", "Sample Flag"]
    for col, header in enumerate(lob_headers):
        lob_ws.write(3, col, header, f["header"])
    for position in range(lob_capacity):
        row, erow = position + 4, position + 5
        lob = lobs[position] if position < len(lobs) else ""
        lob_ws.write(row, 0, lob, f["input"])
        expressions = [
            f'=IF($A{erow}="","",SUMIFS(tblPCSAgent[Eligible Calls Day],tblPCSAgent[LOB],$A{erow}))',
            f'=IF($A{erow}="","",SUMIFS(tblPCSAgent[Q1 Nonblank Day],tblPCSAgent[LOB],$A{erow}))',
            f'=IF($A{erow}="","",SUMIFS(tblPCSAgent[Valid Q1 Day],tblPCSAgent[LOB],$A{erow}))',
            f'=IFERROR(SUMPRODUCT((tblPCSAgent[LOB]=$A{erow})*tblPCSAgent[Valid Q1 Day]*tblPCSAgent[PCS Average Day])/D{erow},"")',
            f'=IF($A{erow}="","",SUMIFS(tblPCSAgent[<=3 Day],tblPCSAgent[LOB],$A{erow}))',
            f'=IF($A{erow}="","",SUMIFS(tblPCSAgent[>3 Day],tblPCSAgent[LOB],$A{erow}))',
            f'=IFERROR(C{erow}/B{erow},"")', f'=IFERROR(D{erow}/B{erow},"")',
            f'=IF($A{erow}="","",SUMIFS(tblPCSAgent[Eligible Calls 3H],tblPCSAgent[LOB],$A{erow}))',
            f'=IF($A{erow}="","",SUMIFS(tblPCSAgent[Valid Q1 3H],tblPCSAgent[LOB],$A{erow}))',
            f'=IFERROR(SUMPRODUCT((tblPCSAgent[LOB]=$A{erow})*tblPCSAgent[Valid Q1 3H]*tblPCSAgent[PCS Average 3H])/K{erow},"")',
            f'=IFERROR(SUMIFS(tblPCSAgent[Q1 Nonblank 3H],tblPCSAgent[LOB],$A{erow})/J{erow},"")',
            f'=IFERROR(K{erow}/J{erow},"")',
            f'=IF($A{erow}="","",IF(K{erow}=0,"NO VALID SURVEY",IF(K{erow}<20,"LOW SAMPLE","OK")))',
        ]
        formats = ["int", "int", "int", "dec", "int", "int", "pct", "pct", "int", "int", "dec", "pct", "pct", "body"]
        for col, (formula, fmt) in enumerate(zip(expressions, formats), 1):
            lob_ws.write_formula(row, col, formula, f[fmt], "")
    lob_ws.add_table(3, 0, 3 + lob_capacity, len(lob_headers) - 1, {
        "name": "tblPCSLob", "style": "Table Style Light 9",
        "columns": [{"header": h, "header_format": f["header"]} for h in lob_headers],
    })
    lob_ws.freeze_panes(4, 1)
    lob_ws.set_column("A:A", 20)
    lob_ws.set_column("B:O", 18)

    management = book.sheet("PCS_REPORT", "PCS management report",
                            "Daily cumulative view and selected three-hour interval using the original PCS definitions.", 11)
    management.set_column("A:L", 14)
    book.banner(management, 3, 0, 11,
                "PASTE CURRENT CALL DATA → CHECK DATA_QUALITY → SEND THIS MANAGEMENT VIEW", "good")
    day_eligible = _count_formula("SETUP!$B$5", "SETUP!$B$5+1", ',tblPCSInput[PCSStatus],1')
    day_nonblank = _count_formula("SETUP!$B$5", "SETUP!$B$5+1", ',tblPCSInput[Question 1],"<>"')
    day_valid = _count_formula("SETUP!$B$5", "SETUP!$B$5+1", ',tblPCSInput[Valid Q1],">=1"')
    day_sum = 'SUMIFS(tblPCSInput[Valid Q1],tblPCSInput[Call Date/Time],">="&SETUP!$B$5,tblPCSInput[Call Date/Time],"<"&SETUP!$B$5+1,tblPCSInput[Call Direction],"I")'
    win_eligible = _count_formula("SETUP!$B$6", "SETUP!$B$7", ',tblPCSInput[PCSStatus],1')
    win_nonblank = _count_formula("SETUP!$B$6", "SETUP!$B$7", ',tblPCSInput[Question 1],"<>"')
    win_valid = _count_formula("SETUP!$B$6", "SETUP!$B$7", ',tblPCSInput[Valid Q1],">=1"')
    win_sum = 'SUMIFS(tblPCSInput[Valid Q1],tblPCSInput[Call Date/Time],">="&SETUP!$B$6,tblPCSInput[Call Date/Time],"<"&SETUP!$B$7,tblPCSInput[Call Direction],"I")'
    book.kpi(management, 0, 5, "DAY PCS AVERAGE", "", f'=IFERROR({day_sum}/{day_valid},"")', "kpi")
    book.kpi(management, 2, 5, "DAY PARTICIPATION", "", f'=IFERROR({day_nonblank}/{day_eligible},"")', "kpi_pct")
    book.kpi(management, 4, 5, "DAY VALID RESPONSES", "", f'=IFERROR({day_valid}/{day_eligible},"")', "kpi_pct")
    book.kpi(management, 6, 5, "3H PCS AVERAGE", "", f'=IFERROR({win_sum}/{win_valid},"")', "kpi")
    book.kpi(management, 8, 5, "3H PARTICIPATION", "", f'=IFERROR({win_nonblank}/{win_eligible},"")', "kpi_pct")
    book.kpi(management, 10, 5, "3H VALID RESPONSES", "", f'=IFERROR({win_valid}/{win_eligible},"")', "kpi_pct")
    management.write("A11", "Reporting window", f["section"])
    management.write("A12", "Report date", f["body"])
    management.write_formula("B12", "=SETUP!B5", f["date"], report_date)
    management.write("A13", "Window start", f["body"])
    management.write_formula("B13", "=SETUP!B6", f["datetime"], window_start)
    management.write("A14", "Window end", f["body"])
    management.write_formula("B14", "=SETUP!B7", f["datetime"], window_end)
    management.write("A15", "Data through", f["body"])
    management.write_formula("B15", "=SETUP!B11", f["datetime"], "")
    management.write("A17", "LOB", f["header"])
    management.write("B17", "3H eligible", f["header"])
    management.write("C17", "3H valid", f["header"])
    management.write("D17", "3H PCS avg", f["header"])
    management.write("E17", "3H participation", f["header"])
    for position in range(lob_capacity):
        row, erow = position + 17, position + 18
        management.write_formula(row, 0, f'=LOB_SUMMARY!A{position+5}', f["body"], lobs[position] if position < len(lobs) else "")
        management.write_formula(row, 1, f'=LOB_SUMMARY!J{position+5}', f["int"], "")
        management.write_formula(row, 2, f'=LOB_SUMMARY!K{position+5}', f["int"], "")
        management.write_formula(row, 3, f'=LOB_SUMMARY!L{position+5}', f["dec"], "")
        management.write_formula(row, 4, f'=LOB_SUMMARY!M{position+5}', f["pct"], "")
    pcs_chart = wb.add_chart({"type": "column"})
    pcs_chart.add_series({"name": "3H PCS average", "categories": ["PCS_REPORT", 17, 0, 16 + lob_capacity, 0],
                          "values": ["PCS_REPORT", 17, 3, 16 + lob_capacity, 3],
                          "fill": {"color": COLORS["teal"]}, "border": {"none": True}})
    pcs_chart.set_title({"name": "Three-hour PCS average by LOB"})
    pcs_chart.set_y_axis({"min": 1, "max": 5, "major_unit": 1})
    pcs_chart.set_legend({"none": True})
    pcs_chart.set_style(10)
    management.insert_chart("G11", pcs_chart, {"x_scale": 1.17, "y_scale": 1.10})

    quality = book.sheet("DATA_QUALITY", "PCS data quality",
                         "Do not send the report until source coverage and roster matching are understood.", 7)
    quality_rows = [
        ("Input call legs", '=COUNT(tblPCSInput[Call Date/Time])', "Every row is a call leg, not necessarily a unique customer call."),
        ("Inbound legs", '=COUNTIF(tblPCSInput[Call Direction],"I")', "Only inbound legs enter PCS calculations."),
        ("Unmatched agents", '=COUNTIF(tblPCSInput[Data Issue],"UNMATCHED AGENT")', "Update ROSTER or correct Agent ID before sending."),
        ("Missing Agent ID", '=COUNTIF(tblPCSInput[Data Issue],"MISSING AGENT ID")', "Agent detail cannot be produced."),
        ("Invalid nonblank Q1", '=COUNTIF(tblPCSInput[Data Issue],"INVALID Q1")', "Participation counts these; PCS average excludes them."),
        ("Duplicate Call IDs", '=SUMPRODUCT(--(tblPCSInput[Call ID]<>""),--(COUNTIF(tblPCSInput[Call ID],tblPCSInput[Call ID])>1))', "Review call legs; do not deduplicate transfers blindly."),
        ("Data through", '=IFERROR(MAX(tblPCSInput[Call Date/Time]),"")', "Must cover the selected window before it is described as complete."),
    ]
    quality.write("A4", "Control", f["header"])
    quality.write("B4", "Result", f["header"])
    quality.write("C4", "Meaning", f["header"])
    for index, (label, formula, meaning) in enumerate(quality_rows, 4):
        quality.write(index, 0, label, f["body"])
        quality.write_formula(index, 1, formula, f["body"], "")
        quality.write(index, 2, meaning, f["note"])
        quality.set_row(index, 30)
    quality.set_column("A:A", 25)
    quality.set_column("B:B", 20)
    quality.set_column("C:C", 75)

    logic = book.sheet("FORMULA_LOGIC", "PCS calculation logic",
                       "Definitions are taken from the original PCS Report.xlsx O15:R15 model.", 8)
    logic_rows = [
        ("Call leg", "One row in Call-by-Call. A transfer can create multiple legs; the template does not deduplicate them."),
        ("Eligible PCS calls", "Inbound call legs where PCSStatus = 1."),
        ("Valid Q1", "Question 1 is numeric and exactly one of 1, 2, 3, 4, or 5."),
        ("PCS Average (original O)", "Sum of Valid Q1 ÷ Valid Q1 count. Blank when there is no valid response."),
        ("<=3 (original P)", "Count of valid Q1 scores 1–3."),
        (">3 (original Q)", "Count of valid Q1 scores 4–5."),
        ("PCS Participation (original R)", "Inbound Q1 nonblank count ÷ inbound PCSStatus=1 count. Nonnumeric responses remain in the numerator exactly as in the original."),
        ("Valid Response Rate", "Valid Q1 count ÷ inbound PCSStatus=1 count. This is intentionally separate from participation."),
        ("Daily cumulative", "Selected report date from 00:00 inclusive to next day 00:00 exclusive."),
        ("Three-hour interval", "Call Date/Time >= Window Start and < Window End. Keep the original timestamp when pasting."),
        ("LOB aggregation", "Sum numerators and denominators first; never average agent percentages or agent averages."),
        ("Actions Rate", "Removed. The original S column was an external link to a missing personal workbook and was not a PCS calculation."),
    ]
    logic.write("A4", "Term", f["header"])
    logic.write("B4", "Exact definition", f["header"])
    for index, (term_name, definition) in enumerate(logic_rows, 4):
        logic.write(index, 0, term_name, f["body"])
        logic.write(index, 1, definition, f["note"])
        logic.set_row(index, 34)
    logic.set_column("A:A", 31)
    logic.set_column("B:B", 100)
    logic.write("A19", "Original O15", f["section"])
    logic.merge_range("A20:I21", '=IFERROR(AVERAGEIFS(RDATA!BO:BO,RDATA!C:C,report_date,RDATA!T:T,agent_id),"")', f["note"])
    logic.write("A23", "Original R15", f["section"])
    logic.merge_range("A24:I26", '=IFERROR(Q1_nonblank_rows / PCSStatus_1_rows,"")', f["note"])

    email = book.sheet("EMAIL_BRIEF", "Three-hour PCS email brief",
                       "Copy, refresh the figures in Excel, and paste into the management email.", 7)
    email.set_column("A:A", 18)
    email.set_column("B:H", 18)
    email.write("A4", "Subject", f["header"])
    email.merge_range("B4:H4", "PCS update | [LOB] | [date] | [window]", f["input"])
    email.write("A6", "Body", f["header"])
    email.merge_range("B6:H18",
                      "Hello,\n\nPlease find attached the latest PCS update. The report shows both the cumulative day and the selected three-hour interval. PCS average uses only valid Q1 scores 1–5. PCS participation is the original nonblank-Q1 / PCSStatus=1 definition; Valid Response Rate is shown separately.\n\nPlease review PCS_REPORT for the management view and DATA_QUALITY for source coverage.\n\nRegards,\nAnass ASSRI",
                      f["note"])

    for ws in (setup, roster_ws, input_ws, details, lob_ws, management, quality, logic, email):
        ws.set_landscape()
        ws.fit_to_pages(1, 0)
        ws.set_footer("&LWFMHub | made by Anass ASSRI&CPage &P of &N&RConfidential")
    management.activate()
    management.select()
    return book.close()


def build_shared_report(kind: str, source: Path | None, output: Path,
                        report_date: date | None = None) -> Path:
    if kind == "bonus":
        if source is None:
            raise ValueError("Bonus report requires a source workbook")
        return build_bonus_management(source, output)
    if kind == "pcs":
        return build_pcs_management(source, output, report_date)
    raise ValueError("Shared report kind must be 'bonus' or 'pcs'")
