/// Disconnected month selector for explicit historical comparisons without intersecting the active Date filter.
table 'Comparison Period'

	column 'Comparison Period'
		dataType: string
		summarizeBy: none
		sourceColumn: Comparison Period

	column 'Month Start'
		dataType: dateTime
		isHidden
		isAvailableInMdx: false
		summarizeBy: none
		sourceColumn: Month Start

	column 'Sort Order'
		dataType: int64
		isHidden
		isAvailableInMdx: false
		summarizeBy: none
		sourceColumn: Sort Order

	partition 'Comparison Period' = m
		mode: import
		source =
			let
			    Source = Csv.Document(File.Contents(HubRoot & "\Feed\PowerBI\DimComparisonPeriod.csv"), [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
			    Promoted = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
			    Selected = Table.SelectColumns(Promoted, {"Comparison Period", "Month Start", "Sort Order"}, MissingField.Error),
			    NullBlanks = Table.ReplaceValue(Selected, "", null, Replacer.ReplaceValue, {"Month Start", "Sort Order"}),
			    Typed = Table.TransformColumnTypes(NullBlanks, {{"Comparison Period", type text}, {"Month Start", type date}, {"Sort Order", Int64.Type}}, "en-US")
			in
			    Typed

	annotation PBI_ResultType = Table
