/// Verint Volume and Absolute Required FTE at native 15-minute Staff Type grain.
table 'Forecast'

	/// Summed Verint forecast demand at native interval grain.
	measure 'Forecast Volume' = ```
			SUM('Forecast'[Volume Forecast])
			```
		formatString: #,##0
		displayFolder: 'Forecast'

	/// Volume-weighted forecast AHT at native interval grain.
	measure 'Forecast AHT Seconds' = ```
			DIVIDE(SUMX('Forecast', 'Forecast'[Volume Forecast] * 'Forecast'[AHT Forecast Seconds]), [Forecast Volume])
			```
		formatString: #,##0
		displayFolder: 'Forecast'

	/// Average summed required FTE across selected date/time intervals.
	measure 'Required FTE' = ```
			AVERAGEX(SUMMARIZE('Forecast', 'Forecast'[Date], 'Forecast'[Time Slot], "Interval FTE", SUM('Forecast'[FTE Required])), [Interval FTE])
			```
		formatString: #,##0.0
		displayFolder: 'Forecast'

	/// Native forecast intervals containing an explicit Verint required-FTE value.
	measure 'Requirement Intervals' = ```
			COUNT('Forecast'[FTE Required])
			```
		formatString: #,##0
		displayFolder: 'Forecast'

	/// Native Staff Type intervals present in the selected forecast extract.
	measure 'Expected Requirement Intervals' = ```
			COUNTROWS('Forecast')
			```
		formatString: #,##0
		displayFolder: 'Forecast'

	/// Intervals with explicit required FTE divided by supplied Staff Type intervals.
	measure 'Requirement Coverage %' = ```
			DIVIDE([Requirement Intervals], [Expected Requirement Intervals])
			```
		formatString: 0.0%
		displayFolder: 'Forecast'

	/// Native-interval required FTE converted to additive FTE-hours.
	measure 'Required FTE Hours' = ```
			SUMX('Forecast', 'Forecast'[FTE Required] * DIVIDE('Forecast'[Interval Minutes], 60))
			```
		formatString: #,##0.0
		displayFolder: 'Forecast'

	/// Peak summed explicit required FTE in the selected horizon.
	measure 'Peak Required FTE' = ```
			MAXX(SUMMARIZE('Forecast', 'Forecast'[Date], 'Forecast'[Time Slot], "Interval FTE", SUM('Forecast'[FTE Required])), [Interval FTE])
			```
		formatString: #,##0.0
		displayFolder: 'Forecast'

	column 'Date'
		dataType: dateTime
		isHidden
		isAvailableInMdx: false
		summarizeBy: none
		sourceColumn: Date

	column 'Interval Start'
		dataType: string
		summarizeBy: none
		sourceColumn: Interval Start

	column 'Interval End'
		dataType: string
		summarizeBy: none
		sourceColumn: Interval End

	column 'Interval Minutes'
		dataType: int64
		isHidden
		isAvailableInMdx: false
		summarizeBy: none
		sourceColumn: Interval Minutes

	column 'Time Slot'
		dataType: int64
		isHidden
		isAvailableInMdx: false
		summarizeBy: none
		sourceColumn: Time Slot

	column 'Staff Type Key'
		dataType: string
		isHidden
		isAvailableInMdx: false
		summarizeBy: none
		sourceColumn: Staff Type Key

	column 'Source Staff Type'
		dataType: string
		summarizeBy: none
		sourceColumn: Source Staff Type

	column 'Staff Type'
		dataType: string
		summarizeBy: none
		sourceColumn: Staff Type

	column 'Planning Group'
		dataType: string
		summarizeBy: none
		sourceColumn: Planning Group

	column 'Management LOB'
		dataType: string
		isHidden
		isAvailableInMdx: false
		summarizeBy: none
		sourceColumn: Management LOB

	column 'Capacity Mapping Status'
		dataType: string
		summarizeBy: none
		sourceColumn: Capacity Mapping Status

	column 'Volume Forecast'
		dataType: decimal
		isHidden
		isAvailableInMdx: false
		summarizeBy: none
		sourceColumn: Volume Forecast

	column 'Abandons Forecast'
		dataType: decimal
		isHidden
		isAvailableInMdx: false
		summarizeBy: none
		sourceColumn: Abandons Forecast

	column 'FTE Forecast'
		dataType: decimal
		isHidden
		isAvailableInMdx: false
		summarizeBy: none
		sourceColumn: FTE Forecast

	column 'FTE Required'
		dataType: decimal
		isHidden
		isAvailableInMdx: false
		summarizeBy: none
		sourceColumn: FTE Required

	column 'Headcount Forecast'
		dataType: decimal
		isHidden
		isAvailableInMdx: false
		summarizeBy: none
		sourceColumn: Headcount Forecast

	column 'Net Staffing Forecast'
		dataType: decimal
		isHidden
		isAvailableInMdx: false
		summarizeBy: none
		sourceColumn: Net Staffing Forecast

	column 'SL Forecast'
		dataType: decimal
		isHidden
		isAvailableInMdx: false
		summarizeBy: none
		sourceColumn: SL Forecast

	column 'SL Required'
		dataType: decimal
		isHidden
		isAvailableInMdx: false
		summarizeBy: none
		sourceColumn: SL Required

	column 'AHT Forecast Seconds'
		dataType: decimal
		isHidden
		isAvailableInMdx: false
		summarizeBy: none
		sourceColumn: AHT Forecast Seconds

	column 'Source File'
		dataType: string
		summarizeBy: none
		sourceColumn: Source File

	partition 'Forecast' = m
		mode: import
		source =
			let
			    Source = Csv.Document(File.Contents(HubRoot & "\Feed\PowerBI\FactForecastInterval.csv"), [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
			    Promoted = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
			    Selected = Table.SelectColumns(Promoted, {"Date", "Interval Start", "Interval End", "Interval Minutes", "Time Slot", "Staff Type Key", "Source Staff Type", "Staff Type", "Planning Group", "Management LOB", "Capacity Mapping Status", "Volume Forecast", "Abandons Forecast", "FTE Forecast", "FTE Required", "Headcount Forecast", "Net Staffing Forecast", "SL Forecast", "SL Required", "AHT Forecast Seconds", "Source File"}, MissingField.Error),
			    NullBlanks = Table.ReplaceValue(Selected, "", null, Replacer.ReplaceValue, {"Date", "Interval Minutes", "Time Slot", "Volume Forecast", "Abandons Forecast", "FTE Forecast", "FTE Required", "Headcount Forecast", "Net Staffing Forecast", "SL Forecast", "SL Required", "AHT Forecast Seconds"}),
			    Typed = Table.TransformColumnTypes(NullBlanks, {{"Date", type date}, {"Interval Start", type text}, {"Interval End", type text}, {"Interval Minutes", Int64.Type}, {"Time Slot", Int64.Type}, {"Staff Type Key", type text}, {"Source Staff Type", type text}, {"Staff Type", type text}, {"Planning Group", type text}, {"Management LOB", type text}, {"Capacity Mapping Status", type text}, {"Volume Forecast", type number}, {"Abandons Forecast", type number}, {"FTE Forecast", type number}, {"FTE Required", type number}, {"Headcount Forecast", type number}, {"Net Staffing Forecast", type number}, {"SL Forecast", type number}, {"SL Required", type number}, {"AHT Forecast Seconds", type number}, {"Source File", type text}}, "en-US")
			in
			    Typed

	annotation PBI_ResultType = Table
