/// Verint forecast at its native 15-minute queue interval.
table 'Forecast'

	/// Summed Verint forecast demand at native interval grain.
	measure 'Forecast Volume' = ```
			SUM('Forecast'[Volume Forecast])
			```
		formatString: #,##0
		displayFolder: 'Forecast'

	/// Average summed required FTE across selected date/time intervals.
	measure 'Required FTE' = ```
			AVERAGEX(SUMMARIZE('Forecast', 'Forecast'[Date], 'Forecast'[Time Slot], "Interval FTE", SUM('Forecast'[FTE Required])), [Interval FTE])
			```
		formatString: #,##0.0
		displayFolder: 'Forecast'

	/// Native forecast intervals containing an explicit Verint required-FTE value.
	measure 'Requirement Intervals' = ```
			COUNT('Forecast'[FTE Required])
			```
		formatString: #,##0
		displayFolder: 'Forecast'

	column 'Date'
		dataType: dateTime
		isHidden
		isAvailableInMdx: false
		summarizeBy: none
		sourceColumn: Date

	column 'Time Slot'
		dataType: int64
		isHidden
		isAvailableInMdx: false
		summarizeBy: none
		sourceColumn: Time Slot

	column 'Queue'
		dataType: string
		isHidden
		isAvailableInMdx: false
		summarizeBy: none
		sourceColumn: Queue

	column 'Volume Forecast'
		dataType: decimal
		isHidden
		isAvailableInMdx: false
		summarizeBy: none
		sourceColumn: Volume Forecast

	column 'FTE Required'
		dataType: decimal
		isHidden
		isAvailableInMdx: false
		summarizeBy: none
		sourceColumn: FTE Required

	column 'SL Forecast'
		dataType: decimal
		isHidden
		isAvailableInMdx: false
		summarizeBy: none
		sourceColumn: SL Forecast

	column 'SL Required'
		dataType: decimal
		isHidden
		isAvailableInMdx: false
		summarizeBy: none
		sourceColumn: SL Required

	column 'AHT Forecast Seconds'
		dataType: decimal
		isHidden
		isAvailableInMdx: false
		summarizeBy: none
		sourceColumn: AHT Forecast Seconds

	column 'Service Scope'
		dataType: string
		summarizeBy: none
		sourceColumn: Service Scope

	column 'Management LOB'
		dataType: string
		isHidden
		isAvailableInMdx: false
		summarizeBy: none
		sourceColumn: Management LOB

	column 'Mapping Status'
		dataType: string
		summarizeBy: none
		sourceColumn: Mapping Status

	column 'Source File'
		dataType: string
		summarizeBy: none
		sourceColumn: Source File

	partition 'Forecast' = m
		mode: import
		source =
			let
			    Source = Csv.Document(File.Contents(HubRoot & "\Feed\PowerBI\FactForecastInterval.csv"), [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
			    Promoted = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
			    Selected = Table.SelectColumns(Promoted, {"Date", "Time Slot", "Queue", "Volume Forecast", "FTE Required", "SL Forecast", "SL Required", "AHT Forecast Seconds", "Service Scope", "Management LOB", "Mapping Status", "Source File"}, MissingField.Error),
			    NullBlanks = Table.ReplaceValue(Selected, "", null, Replacer.ReplaceValue, {"Date", "Time Slot", "Volume Forecast", "FTE Required", "SL Forecast", "SL Required", "AHT Forecast Seconds"}),
			    Typed = Table.TransformColumnTypes(NullBlanks, {{"Date", type date}, {"Time Slot", Int64.Type}, {"Queue", type text}, {"Volume Forecast", type number}, {"FTE Required", type number}, {"SL Forecast", type number}, {"SL Required", type number}, {"AHT Forecast Seconds", type number}, {"Service Scope", type text}, {"Management LOB", type text}, {"Mapping Status", type text}, {"Source File", type text}}, "en-US")
			in
			    Typed

	annotation PBI_ResultType = Table
