/// One compact intraday queue combining capacity gaps and attendance call/follow-up facts.
table 'Operational Action'

	/// Current capacity and attendance facts requiring operational attention.
	measure 'Operational Actions' = ```
			COUNTROWS('Operational Action')
			```
		formatString: #,##0
		displayFolder: 'Intraday'

	column 'Date'
		dataType: dateTime
		isHidden
		isAvailableInMdx: false
		summarizeBy: none
		sourceColumn: Date

	column 'Time Slot'
		dataType: int64
		isHidden
		isAvailableInMdx: false
		summarizeBy: none
		sourceColumn: Time Slot

	column 'State'
		dataType: string
		summarizeBy: none
		sourceColumn: State

	column 'Item'
		dataType: string
		summarizeBy: none
		sourceColumn: Item

	column 'Agent ID'
		dataType: string
		isHidden
		isAvailableInMdx: false
		summarizeBy: none
		sourceColumn: Agent ID

	column 'Agent'
		dataType: string
		summarizeBy: none
		sourceColumn: Agent

	column 'Team Leader'
		dataType: string
		summarizeBy: none
		sourceColumn: Team Leader

	column 'Management LOB'
		dataType: string
		isHidden
		isAvailableInMdx: false
		summarizeBy: none
		sourceColumn: Management LOB

	column 'Planning Group'
		dataType: string
		summarizeBy: none
		sourceColumn: Planning Group

	column 'Staff Type'
		dataType: string
		summarizeBy: none
		sourceColumn: Staff Type

	column 'Staff Type Key'
		dataType: string
		isHidden
		isAvailableInMdx: false
		summarizeBy: none
		sourceColumn: Staff Type Key

	column 'Required FTE'
		dataType: decimal
		sourceColumn: Required FTE

	column 'Resource FTE'
		dataType: decimal
		sourceColumn: Resource FTE

	column 'Variance FTE'
		dataType: decimal
		sourceColumn: Variance FTE

	column 'Detail'
		dataType: string
		summarizeBy: none
		sourceColumn: Detail

	column 'Evidence'
		dataType: string
		summarizeBy: none
		sourceColumn: Evidence

	column 'Priority Sort'
		dataType: int64
		isHidden
		isAvailableInMdx: false
		summarizeBy: none
		sourceColumn: Priority Sort

	partition 'Operational Action' = m
		mode: import
		source =
			let
			    Source = Csv.Document(File.Contents(HubRoot & "\Feed\PowerBI\FactOperationalAction.csv"), [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
			    Promoted = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
			    Selected = Table.SelectColumns(Promoted, {"Date", "Time Slot", "State", "Item", "Agent ID", "Agent", "Team Leader", "Management LOB", "Planning Group", "Staff Type", "Staff Type Key", "Required FTE", "Resource FTE", "Variance FTE", "Detail", "Evidence", "Priority Sort"}, MissingField.Error),
			    NullBlanks = Table.ReplaceValue(Selected, "", null, Replacer.ReplaceValue, {"Date", "Time Slot", "Required FTE", "Resource FTE", "Variance FTE", "Priority Sort"}),
			    Typed = Table.TransformColumnTypes(NullBlanks, {{"Date", type date}, {"Time Slot", Int64.Type}, {"State", type text}, {"Item", type text}, {"Agent ID", type text}, {"Agent", type text}, {"Team Leader", type text}, {"Management LOB", type text}, {"Planning Group", type text}, {"Staff Type", type text}, {"Staff Type Key", type text}, {"Required FTE", type number}, {"Resource FTE", type number}, {"Variance FTE", type number}, {"Detail", type text}, {"Evidence", type text}, {"Priority Sort", Int64.Type}}, "en-US")
			in
			    Typed

	annotation PBI_ResultType = Table
