/// Exact low-score call queue with Call ID for coaching follow-up.
table 'PCS Coaching'

	/// Low-score call-level cases available for coaching follow-up.
	measure 'Coaching Cases' = ```
			COUNTROWS('PCS Coaching')
			```
		formatString: #,##0
		displayFolder: 'PCS coaching'

	column 'Date'
		dataType: dateTime
		isHidden
		isAvailableInMdx: false
		summarizeBy: none
		sourceColumn: Date

	column 'Call Start'
		dataType: string
		summarizeBy: none
		sourceColumn: Call Start

	column 'Agent ID'
		dataType: string
		isHidden
		isAvailableInMdx: false
		summarizeBy: none
		sourceColumn: Agent ID

	column 'Agent'
		dataType: string
		summarizeBy: none
		sourceColumn: Agent

	column 'Team Leader'
		dataType: string
		summarizeBy: none
		sourceColumn: Team Leader

	column 'LOB'
		dataType: string
		summarizeBy: none
		sourceColumn: LOB

	column 'Management LOB'
		dataType: string
		isHidden
		isAvailableInMdx: false
		summarizeBy: none
		sourceColumn: Management LOB

	column 'Call ID'
		dataType: string
		summarizeBy: none
		sourceColumn: Call ID

	column 'Call Key'
		dataType: string
		isHidden
		isAvailableInMdx: false
		summarizeBy: none
		sourceColumn: Call Key

	column 'Q1 Score'
		dataType: decimal
		sourceColumn: Q1 Score

	column 'Customer Comment'
		dataType: string
		summarizeBy: none
		sourceColumn: Customer Comment

	column 'PCS Status'
		dataType: string
		summarizeBy: none
		sourceColumn: PCS Status

	partition 'PCS Coaching' = m
		mode: import
		source =
			let
			    Source = Csv.Document(File.Contents(HubRoot & "\Feed\PowerBI\FactPCSCoaching.csv"), [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
			    Promoted = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
			    Selected = Table.SelectColumns(Promoted, {"Date", "Call Start", "Agent ID", "Agent", "Team Leader", "LOB", "Management LOB", "Call ID", "Call Key", "Q1 Score", "Customer Comment", "PCS Status"}, MissingField.Error),
			    NullBlanks = Table.ReplaceValue(Selected, "", null, Replacer.ReplaceValue, {"Date", "Q1 Score"}),
			    Typed = Table.TransformColumnTypes(NullBlanks, {{"Date", type date}, {"Call Start", type text}, {"Agent ID", type text}, {"Agent", type text}, {"Team Leader", type text}, {"LOB", type text}, {"Management LOB", type text}, {"Call ID", type text}, {"Call Key", type text}, {"Q1 Score", type number}, {"Customer Comment", type text}, {"PCS Status", type text}}, "en-US")
			in
			    Typed

	annotation PBI_ResultType = Table
