/// Ordered native stacked-bar segments for published schedule and Agent Status actual bands.
table 'Shift Placement'

	/// Ordered segment duration used by the native schedule review timeline.
	measure 'Timeline Duration Hours' = ```
			SUM('Shift Placement'[Duration Hours])
			```
		formatString: 0.0
		displayFolder: 'Schedule integrity'

	column 'Date'
		dataType: dateTime
		isHidden
		isAvailableInMdx: false
		summarizeBy: none
		sourceColumn: Date

	column 'Placement Key'
		dataType: string
		isHidden
		isAvailableInMdx: false
		summarizeBy: none
		sourceColumn: Placement Key

	column 'Agent Day Key'
		dataType: string
		isHidden
		isAvailableInMdx: false
		summarizeBy: none
		sourceColumn: Agent Day Key

	column 'Agent ID'
		dataType: string
		isHidden
		isAvailableInMdx: false
		summarizeBy: none
		sourceColumn: Agent ID

	column 'Agent'
		dataType: string
		summarizeBy: none
		sourceColumn: Agent

	column 'Team Leader'
		dataType: string
		summarizeBy: none
		sourceColumn: Team Leader

	column 'Management LOB'
		dataType: string
		isHidden
		isAvailableInMdx: false
		summarizeBy: none
		sourceColumn: Management LOB

	column 'Row Label'
		dataType: string
		summarizeBy: none
		sourceColumn: Row Label

	column 'Row Sort'
		dataType: string
		isHidden
		isAvailableInMdx: false
		summarizeBy: none
		sourceColumn: Row Sort

	column 'Band'
		dataType: string
		summarizeBy: none
		sourceColumn: Band

	column 'Band Sort'
		dataType: int64
		isHidden
		isAvailableInMdx: false
		summarizeBy: none
		sourceColumn: Band Sort

	column 'Segment Order'
		dataType: int64
		isHidden
		isAvailableInMdx: false
		summarizeBy: none
		sourceColumn: Segment Order

	column 'Segment Type'
		dataType: string
		summarizeBy: none
		sourceColumn: Segment Type

	column 'Segment Series'
		dataType: string
		isHidden
		isAvailableInMdx: false
		summarizeBy: none
		sourceColumn: Segment Series

	column 'Duration Hours'
		dataType: decimal
		isHidden
		isAvailableInMdx: false
		summarizeBy: none
		sourceColumn: Duration Hours

	column 'Segment Color'
		dataType: string
		isHidden
		isAvailableInMdx: false
		summarizeBy: none
		sourceColumn: Segment Color

	column 'Classification'
		dataType: string
		summarizeBy: none
		sourceColumn: Classification

	column 'Requires Review'
		dataType: int64
		sourceColumn: Requires Review

	partition 'Shift Placement' = m
		mode: import
		source =
			let
			    Source = Csv.Document(File.Contents(HubRoot & "\Feed\PowerBI\FactShiftPlacement.csv"), [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
			    Promoted = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
			    Selected = Table.SelectColumns(Promoted, {"Date", "Placement Key", "Agent Day Key", "Agent ID", "Agent", "Team Leader", "Management LOB", "Row Label", "Row Sort", "Band", "Band Sort", "Segment Order", "Segment Type", "Segment Series", "Duration Hours", "Segment Color", "Classification", "Requires Review"}, MissingField.Error),
			    NullBlanks = Table.ReplaceValue(Selected, "", null, Replacer.ReplaceValue, {"Date", "Band Sort", "Segment Order", "Duration Hours", "Requires Review"}),
			    Typed = Table.TransformColumnTypes(NullBlanks, {{"Date", type date}, {"Placement Key", type text}, {"Agent Day Key", type text}, {"Agent ID", type text}, {"Agent", type text}, {"Team Leader", type text}, {"Management LOB", type text}, {"Row Label", type text}, {"Row Sort", type text}, {"Band", type text}, {"Band Sort", Int64.Type}, {"Segment Order", Int64.Type}, {"Segment Type", type text}, {"Segment Series", type text}, {"Duration Hours", type number}, {"Segment Color", type text}, {"Classification", type text}, {"Requires Review", Int64.Type}}, "en-US")
			in
			    Typed

	annotation PBI_ResultType = Table
