/// Scheduled and observed capacity at date, interval, roster LOB and language grain.
table 'Staffing'

	/// Average net scheduled FTE across selected intervals after governed time off.
	measure 'Average Scheduled FTE' = ```
			AVERAGEX(SUMMARIZE('Staffing', 'Staffing'[Date], 'Staffing'[Time Slot], "Interval FTE", SUM('Staffing'[Scheduled FTE])), [Interval FTE])
			```
		formatString: #,##0.0
		displayFolder: 'Capacity'

	/// Peak net scheduled FTE after governed PTO/Away in the selected horizon.
	measure 'Peak Net Scheduled FTE' = ```
			MAXX(SUMMARIZE('Staffing', 'Staffing'[Date], 'Staffing'[Time Slot], "Interval FTE", SUM('Staffing'[Scheduled FTE])), [Interval FTE])
			```
		formatString: #,##0.0
		displayFolder: 'Capacity'

	/// Average elapsed scheduled FTE in completed interval portions.
	measure 'Average Elapsed Scheduled FTE' = ```
			AVERAGEX(SUMMARIZE('Staffing', 'Staffing'[Date], 'Staffing'[Time Slot], "Interval FTE", SUM('Staffing'[Elapsed Scheduled FTE])), [Interval FTE])
			```
		formatString: #,##0.0
		displayFolder: 'Capacity'

	/// Average governed PTO/Away FTE deducted from gross scheduled capacity.
	measure 'PTO / Away FTE' = ```
			AVERAGEX(SUMMARIZE('Staffing', 'Staffing'[Date], 'Staffing'[Time Slot], "Interval FTE", SUM('Staffing'[Planned Time Off FTE])), [Interval FTE])
			```
		formatString: #,##0.0
		displayFolder: 'Capacity'

	/// Average observed FTE across selected completed intervals.
	measure 'Average Observed FTE' = ```
			AVERAGEX(SUMMARIZE('Staffing', 'Staffing'[Date], 'Staffing'[Time Slot], "Interval FTE", SUM('Staffing'[Observed FTE])), [Interval FTE])
			```
		formatString: #,##0.0
		displayFolder: 'Capacity'

	/// Average productive FTE across selected completed intervals.
	measure 'Average Productive FTE' = ```
			AVERAGEX(SUMMARIZE('Staffing', 'Staffing'[Date], 'Staffing'[Time Slot], "Interval FTE", SUM('Staffing'[Productive FTE])), [Interval FTE])
			```
		formatString: #,##0.0
		displayFolder: 'Capacity'

	/// Average scheduled headcount across selected native intervals.
	measure 'Average Scheduled HC' = ```
			AVERAGEX(SUMMARIZE('Staffing', 'Staffing'[Date], 'Staffing'[Time Slot], "Interval HC", SUM('Staffing'[Scheduled HC])), [Interval HC])
			```
		formatString: #,##0.0
		displayFolder: 'Capacity'

	/// Average observed headcount across selected completed intervals.
	measure 'Average Observed HC' = ```
			AVERAGEX(SUMMARIZE('Staffing', 'Staffing'[Date], 'Staffing'[Time Slot], "Interval HC", SUM('Staffing'[Observed HC])), [Interval HC])
			```
		formatString: #,##0.0
		displayFolder: 'Capacity'

	/// Required FTE less average scheduled capacity, floored at zero; blank when Verint requirement is not supplied.
	measure 'Capacity Gap FTE' = ```
			IF(ISBLANK([Required FTE]), BLANK(), MAX([Required FTE] - [Average Scheduled FTE], 0))
			```
		formatString: #,##0.0
		displayFolder: 'Capacity'

	/// Average scheduled capacity less required FTE; blank when Verint requirement is not supplied.
	measure 'Net Capacity Gap FTE' = ```
			IF(ISBLANK([Required FTE]), BLANK(), [Average Scheduled FTE] - [Required FTE])
			```
		formatString: #,##0.0;[Red]-#,##0.0
		displayFolder: 'Capacity'

	/// Average scheduled FTE less average observed FTE, floored at zero.
	measure 'Observed Gap FTE' = ```
			MAX([Average Scheduled FTE] - [Average Observed FTE], 0)
			```
		formatString: #,##0.0
		displayFolder: 'Capacity'

	/// Average scheduled capacity divided by explicit Verint required FTE; blank when requirement is unavailable.
	measure 'Coverage %' = ```
			IF(ISBLANK([Required FTE]), BLANK(), DIVIDE([Average Scheduled FTE], [Required FTE]))
			```
		formatString: 0.0%
		displayFolder: 'Capacity'

	/// Most negative scheduled-minus-required FTE interval; blank requirements remain excluded.
	measure 'Peak Shortage FTE' = ```
			MINX(SUMMARIZECOLUMNS('Date'[Date], 'Time'[Quarter Hour Index], "Gap", IF(ISBLANK([Required FTE]), BLANK(), [Average Scheduled FTE] - [Required FTE])), [Gap])
			```
		formatString: #,##0.0;[Red]-#,##0.0
		displayFolder: 'Capacity'

	/// Selected intervals with more than one FTE scheduled shortage.
	measure 'Critical Intervals' = ```
			COUNTROWS(FILTER(SUMMARIZECOLUMNS('Date'[Date], 'Time'[Quarter Hour Index], "Gap", IF(ISBLANK([Required FTE]), BLANK(), [Average Scheduled FTE] - [Required FTE])), NOT ISBLANK([Gap]) && [Gap] < -1))
			```
		formatString: #,##0
		displayFolder: 'Capacity'

	/// Productive capacity less explicit requirement in the selected operational context.
	measure 'Current Productive Gap FTE' = ```
			IF(ISBLANK([Required FTE]), BLANK(), [Average Productive FTE] - [Required FTE])
			```
		formatString: #,##0.0;[Red]-#,##0.0
		displayFolder: 'Capacity'

	column 'Date'
		dataType: dateTime
		isHidden
		isAvailableInMdx: false
		summarizeBy: none
		sourceColumn: Date

	column 'Time Slot'
		dataType: int64
		isHidden
		isAvailableInMdx: false
		summarizeBy: none
		sourceColumn: Time Slot

	column 'LOB'
		dataType: string
		summarizeBy: none
		sourceColumn: LOB

	column 'Management LOB'
		dataType: string
		isHidden
		isAvailableInMdx: false
		summarizeBy: none
		sourceColumn: Management LOB

	column 'Language'
		dataType: string
		summarizeBy: none
		sourceColumn: Language

	column 'Scheduled HC'
		dataType: int64
		isHidden
		isAvailableInMdx: false
		summarizeBy: none
		sourceColumn: Scheduled HC

	column 'Observed HC'
		dataType: int64
		isHidden
		isAvailableInMdx: false
		summarizeBy: none
		sourceColumn: Observed HC

	column 'Productive HC'
		dataType: int64
		isHidden
		isAvailableInMdx: false
		summarizeBy: none
		sourceColumn: Productive HC

	column 'Auxiliary HC'
		dataType: int64
		isHidden
		isAvailableInMdx: false
		summarizeBy: none
		sourceColumn: Auxiliary HC

	column 'Gross Scheduled FTE'
		dataType: decimal
		isHidden
		isAvailableInMdx: false
		summarizeBy: none
		sourceColumn: Gross Scheduled FTE

	column 'Planned Time Off FTE'
		dataType: decimal
		isHidden
		isAvailableInMdx: false
		summarizeBy: none
		sourceColumn: Planned Time Off FTE

	column 'Scheduled FTE'
		dataType: decimal
		isHidden
		isAvailableInMdx: false
		summarizeBy: none
		sourceColumn: Scheduled FTE

	column 'Elapsed Scheduled FTE'
		dataType: decimal
		isHidden
		isAvailableInMdx: false
		summarizeBy: none
		sourceColumn: Elapsed Scheduled FTE

	column 'Observed FTE'
		dataType: decimal
		isHidden
		isAvailableInMdx: false
		summarizeBy: none
		sourceColumn: Observed FTE

	column 'Productive FTE'
		dataType: decimal
		isHidden
		isAvailableInMdx: false
		summarizeBy: none
		sourceColumn: Productive FTE

	column 'Staffing Variance FTE'
		dataType: decimal
		isHidden
		isAvailableInMdx: false
		summarizeBy: none
		sourceColumn: Staffing Variance FTE

	column 'Staffing Gap FTE'
		dataType: decimal
		isHidden
		isAvailableInMdx: false
		summarizeBy: none
		sourceColumn: Staffing Gap FTE

	column 'Staffing State'
		dataType: string
		summarizeBy: none
		sourceColumn: Staffing State

	column 'Evidence Basis'
		dataType: string
		summarizeBy: none
		sourceColumn: Evidence Basis

	partition 'Staffing' = m
		mode: import
		source =
			let
			    Source = Csv.Document(File.Contents(HubRoot & "\Feed\PowerBI\FactStaffing15Min.csv"), [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
			    Promoted = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
			    Selected = Table.SelectColumns(Promoted, {"Date", "Time Slot", "LOB", "Management LOB", "Language", "Scheduled HC", "Observed HC", "Productive HC", "Auxiliary HC", "Gross Scheduled FTE", "Planned Time Off FTE", "Scheduled FTE", "Elapsed Scheduled FTE", "Observed FTE", "Productive FTE", "Staffing Variance FTE", "Staffing Gap FTE", "Staffing State", "Evidence Basis"}, MissingField.Error),
			    NullBlanks = Table.ReplaceValue(Selected, "", null, Replacer.ReplaceValue, {"Date", "Time Slot", "Scheduled HC", "Observed HC", "Productive HC", "Auxiliary HC", "Gross Scheduled FTE", "Planned Time Off FTE", "Scheduled FTE", "Elapsed Scheduled FTE", "Observed FTE", "Productive FTE", "Staffing Variance FTE", "Staffing Gap FTE"}),
			    Typed = Table.TransformColumnTypes(NullBlanks, {{"Date", type date}, {"Time Slot", Int64.Type}, {"LOB", type text}, {"Management LOB", type text}, {"Language", type text}, {"Scheduled HC", Int64.Type}, {"Observed HC", Int64.Type}, {"Productive HC", Int64.Type}, {"Auxiliary HC", Int64.Type}, {"Gross Scheduled FTE", type number}, {"Planned Time Off FTE", type number}, {"Scheduled FTE", type number}, {"Elapsed Scheduled FTE", type number}, {"Observed FTE", type number}, {"Productive FTE", type number}, {"Staffing Variance FTE", type number}, {"Staffing Gap FTE", type number}, {"Staffing State", type text}, {"Evidence Basis", type text}}, "en-US")
			in
			    Typed

	annotation PBI_ResultType = Table
