/// Governed Verint Staff Type and published-assignment bridge; never a call queue.
table 'Staff Type'

	column 'Staff Type Key'
		dataType: string
		isHidden
		isAvailableInMdx: false
		summarizeBy: none
		sourceColumn: Staff Type Key

	column 'Staff Type'
		dataType: string
		summarizeBy: none
		sourceColumn: Staff Type

	column 'Planning Group'
		dataType: string
		isHidden
		isAvailableInMdx: false
		summarizeBy: none
		sourceColumn: Planning Group

	column 'Management LOB'
		dataType: string
		isHidden
		isAvailableInMdx: false
		summarizeBy: none
		sourceColumn: Management LOB

	column 'Mapping Status'
		dataType: string
		summarizeBy: none
		sourceColumn: Mapping Status

	partition 'Staff Type' = m
		mode: import
		source =
			let
			    Source = Csv.Document(File.Contents(HubRoot & "\Feed\PowerBI\DimStaffType.csv"), [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
			    Promoted = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
			    Selected = Table.SelectColumns(Promoted, {"Staff Type Key", "Staff Type", "Planning Group", "Management LOB", "Mapping Status"}, MissingField.Error),
			    NullBlanks = Table.ReplaceValue(Selected, "", null, Replacer.ReplaceValue, {}),
			    Typed = Table.TransformColumnTypes(NullBlanks, {{"Staff Type Key", type text}, {"Staff Type", type text}, {"Planning Group", type text}, {"Management LOB", type text}, {"Mapping Status", type text}}, "en-US")
			in
			    Typed

	annotation PBI_ResultType = Table
