"use strict";

const $ = (id) => document.getElementById(id);
const state = {meta:null, view:"today", data:null, timer:null};
const pages = {
  today:{title:"Today's Control",kicker:"LIVE CONTROL",subtitle:"What needs attention now, backed by governed evidence."},
  staffing:{title:"Staff Preparation",kicker:"PLAN • SCHEDULE • PROTECT",subtitle:"Explicit requirement versus published net capacity at Staff Type grain."},
  service:{title:"Intraday Service",kicker:"OPERATE • RECOVER",subtitle:"Combined Management LOB service result with exact queue diagnosis."},
  attendance:{title:"Attendance & Schedule Review",kicker:"REVIEW • CORRECT",subtitle:"Published schedule, Agent Status timeline and exact residual gaps."},
  history:{title:"Historical Review",kicker:"LEARN • IMPROVE",subtitle:"Separate service, capacity, final absence and shrinkage evidence."}
};

function node(tag, cls, text){const el=document.createElement(tag);if(cls)el.className=cls;if(text!==undefined)el.textContent=text;return el}
function option(value,label=value){const el=node("option",null,label);el.value=value;return el}
function unique(values){return [...new Set(values.filter(Boolean))].sort((a,b)=>a.localeCompare(b))}
function selected(id){const v=$(id).value;return v&&v!=="All"?v:null}
function fmt(value,kind="text"){
  if(value===null||value===undefined||Number.isNaN(value))return "—";
  if(kind==="percent")return new Intl.NumberFormat("en-GB",{style:"percent",minimumFractionDigits:1,maximumFractionDigits:1}).format(value);
  if(kind==="integer")return new Intl.NumberFormat("en-GB",{maximumFractionDigits:0}).format(value);
  if(kind==="decimal")return new Intl.NumberFormat("en-GB",{minimumFractionDigits:1,maximumFractionDigits:1}).format(value);
  return String(value);
}
function shortDate(value){if(!value)return "—";const d=new Date(value.length===10?`${value}T12:00:00Z`:value);return Number.isNaN(d.getTime())?value:new Intl.DateTimeFormat("en-GB",{day:"2-digit",month:"short",timeZone:"UTC"}).format(d)}
function time(value){if(!value)return "—";return value.includes("T")?value.slice(11,16):value.slice(-8,-3)}
function pill(textValue,cls=""){const span=node("span",`pill ${cls}`,textValue||"—");return span}
function showToast(message,error=false){const t=$("toast");t.textContent=message;t.className=`toast show${error?" error":""}`;clearTimeout(showToast.timer);showToast.timer=setTimeout(()=>t.className="toast",4200)}

async function api(path,options){const response=await fetch(path,options);let data;try{data=await response.json()}catch{data={error:`HTTP ${response.status}`}}if(!response.ok)throw new Error(data.error||`HTTP ${response.status}`);return data}

function setSelect(id,values,current,{allowAll=true}={}){const el=$(id);el.replaceChildren();if(allowAll)el.append(option("All","All"));values.forEach(v=>el.append(option(v)));el.value=values.includes(current)?current:(allowAll?"All":values[0]||"")}
function cascade(changed){
  if(!state.meta)return;
  const lob=selected("lob"), planning=selected("planning"), staff=selected("staff"), leader=selected("leader"), agent=selected("agent");
  const caps=state.meta.capacity.filter(r=>(!lob||r.management_lob===lob));
  const plannings=unique(caps.map(r=>r.planning_group));
  const keepPlanning=changed==="lob"?null:planning;setSelect("planning",plannings,keepPlanning);
  const activePlanning=selected("planning");
  const staffs=unique(caps.filter(r=>!activePlanning||r.planning_group===activePlanning).map(r=>r.staff_type));
  const keepStaff=["lob","planning"].includes(changed)?null:staff;setSelect("staff",staffs,keepStaff);
  const activeStaff=selected("staff");
  const agents=state.meta.agents.filter(r=>(!lob||r.management_lob===lob)&&(!activePlanning||!r.planning_group||r.planning_group===activePlanning)&&(!activeStaff||!r.staff_type||r.staff_type===activeStaff));
  const leaders=unique(agents.map(r=>r.team_leader));
  const keepLeader=["lob","planning","staff"].includes(changed)?null:leader;setSelect("leader",leaders,keepLeader);
  const activeLeader=selected("leader");
  const people=unique(agents.filter(r=>!activeLeader||r.team_leader===activeLeader).map(r=>`${r.name} [${r.id}]`));
  setSelect("agent",people,agent);
}
function query(){
  const p=new URLSearchParams({start:$("start").value,end:$("end").value});
  for(const [id,key] of [["lob","management_lob"],["planning","planning_group"],["staff","staff_type"],["leader","team_leader"]]){const v=selected(id);if(v)p.set(key,v)}
  const label=selected("agent");if(label){const match=label.match(/\[([^\]]+)\]$/);if(match)p.set("agent_id",match[1])}
  return p;
}
function setPeriod(value){
  const latest=new Date(`${state.meta.latest_date}T12:00:00Z`);let start=new Date(latest),end=new Date(latest);
  if(value==="week")start.setUTCDate(start.getUTCDate()-((start.getUTCDay()+6)%7));
  if(value==="month")start.setUTCDate(1);
  if(value==="future")end.setUTCDate(end.getUTCDate()+27);
  if(value!=="custom"){$("start").value=start.toISOString().slice(0,10);$("end").value=end.toISOString().slice(0,10)}
}

function renderCards(cards){const root=$("cards");root.replaceChildren();for(const card of cards||[]){const el=node("article","kpi");el.append(node("div","kpi-label",card.label),node("div","kpi-value",fmt(card.value,card.kind)),node("div","kpi-note",card.note));root.append(el)}}
function panel(title,subtitle,tag="GOVERNED"){const p=node("section","panel");const h=node("header","panel-head");const copy=node("div");copy.append(node("h2",null,title),node("p",null,subtitle));h.append(copy,node("span","panel-tag",tag));p.append(h);return p}
function empty(container,message="No governed rows match this selection."){const e=node("div","chart-empty");e.append(node("b",null,"No data for this scope"),node("small",null,message));container.replaceChildren(e)}
function svg(tag,attrs={}){const el=document.createElementNS("http://www.w3.org/2000/svg",tag);Object.entries(attrs).forEach(([k,v])=>el.setAttribute(k,v));return el}
function lineChart(container,rows,series,{xKey="time",percent=false}={}){
  if(!rows?.length){empty(container);return}const W=800,H=255,p={l:46,r:15,t:15,b:33};const values=rows.flatMap(r=>series.map(s=>r[s.key]).filter(v=>v!==null&&v!==undefined));if(!values.length){empty(container);return}
  let min=percent?0:Math.min(0,...values),max=percent?1:Math.max(...values);if(max===min)max=min+1;const root=svg("svg",{viewBox:`0 0 ${W} ${H}`,preserveAspectRatio:"none"});
  for(let i=0;i<=4;i++){const y=p.t+(H-p.t-p.b)*i/4;root.append(svg("line",{x1:p.l,y1:y,x2:W-p.r,y2:y,stroke:"#e5ebef","stroke-width":"1"}));const label=svg("text",{x:p.l-8,y:y+3,"text-anchor":"end",fill:"#788995","font-size":"9"});label.textContent=percent?`${Math.round((1-i/4)*100)}%`:fmt(max-(max-min)*i/4,"decimal");root.append(label)}
  series.forEach(s=>{let d="";rows.forEach((r,i)=>{const v=r[s.key];if(v===null||v===undefined)return;const x=p.l+(W-p.l-p.r)*(rows.length===1?.5:i/(rows.length-1));const y=p.t+(H-p.t-p.b)*(1-(v-min)/(max-min));d+=`${d?" L":"M"}${x} ${y}`});root.append(svg("path",{d,fill:"none",stroke:s.color,"stroke-width":"2.5","stroke-linejoin":"round","stroke-linecap":"round"}))});
  const ticks=Math.min(7,rows.length);for(let i=0;i<ticks;i++){const index=Math.round(i*(rows.length-1)/Math.max(1,ticks-1));const x=p.l+(W-p.l-p.r)*(rows.length===1?.5:index/(rows.length-1));const t=svg("text",{x,y:H-11,"text-anchor":"middle",fill:"#778995","font-size":"8"});t.textContent=xKey==="date"?shortDate(rows[index][xKey]):time(rows[index][xKey]);root.append(t)}container.replaceChildren(root);
}
function barChart(container,rows,{label,key,percent=false,color="#007c83",secondaryKey=null}={}){
  if(!rows?.length){empty(container);return}const W=520,H=250,p={l:118,r:38,t:12,b:16};const max=Math.max(...rows.map(r=>Math.max(r[key]||0,secondaryKey?r[secondaryKey]||0:0)),percent?1:1);const root=svg("svg",{viewBox:`0 0 ${W} ${H}`,preserveAspectRatio:"none"});const height=Math.min(28,(H-p.t-p.b)/rows.length);rows.slice(0,8).forEach((r,i)=>{const y=p.t+i*(H-p.t-p.b)/Math.min(rows.length,8);const txt=svg("text",{x:p.l-8,y:y+height*.7,"text-anchor":"end",fill:"#405463","font-size":"9","font-weight":"600"});txt.textContent=String(r[label]||"—").slice(0,19);root.append(txt);if(secondaryKey){root.append(svg("rect",{x:p.l,y:y+3,width:(W-p.l-p.r)*(r[secondaryKey]||0)/max,height:height-6,rx:2,fill:"#d5dee4"}))}root.append(svg("rect",{x:p.l,y:y+3,width:(W-p.l-p.r)*(r[key]||0)/max,height:height-6,rx:2,fill:color}));const val=svg("text",{x:W-p.r+4,y:y+height*.7,fill:"#405463","font-size":"8"});val.textContent=fmt(r[key],percent?"percent":"decimal");root.append(val)});container.replaceChildren(root)}
function legend(items){const l=node("div","legend");items.forEach(i=>{const s=node("span");const dot=node("i");dot.style.background=i.color;s.append(dot,document.createTextNode(i.label));l.append(s)});return l}
function makeTable(rows,columns){const wrap=node("div","table-wrap");const table=node("table","data-table");const head=node("thead"),hr=node("tr");columns.forEach(c=>hr.append(node("th",c.align==="right"?"num":"",c.label)));head.append(hr);const body=node("tbody");for(const row of rows||[]){const tr=node("tr");for(const col of columns){const td=node("td",`${col.align==="right"?"num ":""}${col.strong?"strong":""}`);const value=row[col.key];if(col.pill){td.append(pill(col.format?col.format(value,row):value,col.pill(value,row)))}else td.textContent=col.format?col.format(value,row):fmt(value,col.kind);td.title=td.textContent;tr.append(td)}body.append(tr)}table.append(head,body);wrap.append(table);if(!rows?.length){wrap.replaceChildren();const e=node("div","empty-state");e.style.height="180px";e.append(node("b",null,"Nothing requires action"),node("small",null,"No governed detail matches the current scope."));wrap.append(e)}return wrap}
function resultPill(v){const x=String(v||"").toLowerCase();return x.includes("no show")||x.includes("early")?"red":x.includes("unknown")||x.includes("late")?"amber":x.includes("present")?"green":"blue"}

function renderToday(data){const grid=node("div","grid");const p1=panel("Service and demand through the day","15-minute ratio-of-sums across exact Flash queues","LIVE");const chart=node("div","chart");p1.append(chart);lineChart(chart,data.service_timeline,[{key:"service_level",color:"#007c83"},{key:"abandon_rate",color:"#d6a84b"}],{percent:true});p1.querySelector(".panel-head").append(legend([{label:"Service level",color:"#007c83"},{label:"Abandon rate",color:"#d6a84b"}]));
  const p2=panel("LOB pulse","Service level and evidence-backed attendance","TODAY");const c2=node("div","chart");p2.append(c2);barChart(c2,data.service_by_lob,{label:"management_lob",key:"service_level",percent:true});grid.append(p1,p2);
  const p3=panel("Attendance calls and follow-up","Late remains present; unknown is never promoted to no show","ACTION LIST");p3.classList.add("wide");p3.append(makeTable(data.attendance_actions,[{key:"management_lob",label:"LOB",strong:true},{key:"team_leader",label:"Team leader"},{key:"agent",label:"Agent",strong:true},{key:"result",label:"State",pill:resultPill},{key:"scheduled_start",label:"Shift",format:v=>time(v)},{key:"first_login",label:"First seen",format:v=>time(v)},{key:"late_minutes",label:"Late",kind:"integer",align:"right"},{key:"early_leave_minutes",label:"Early",kind:"integer",align:"right"},{key:"action",label:"Action",pill:v=>v&&v!=="NONE"?"amber":"green"},{key:"evidence",label:"Evidence"}]));grid.append(p3);return grid}
function renderStaffing(data){const grid=node("div","grid");const p1=panel("Required versus net scheduled FTE","15-minute capacity; blank requirement remains blank","CAPACITY");const c1=node("div","chart");p1.append(c1);lineChart(c1,data.intervals,[{key:"required_fte",color:"#b42318"},{key:"scheduled_fte",color:"#007c83"},{key:"observed_fte",color:"#d6a84b"}]);p1.querySelector(".panel-head").append(legend([{label:"Required",color:"#b42318"},{label:"Net scheduled",color:"#007c83"},{label:"Observed",color:"#d6a84b"}]));
  const p2=panel("Capacity by Staff Type","Staff Types are workforce planning identities, not queues","STAFF TYPE");const c2=node("div","chart");p2.append(c2);const agg={};data.intervals.forEach(r=>{const a=agg[r.staff_type]??={staff_type:r.staff_type,required_fte:0,scheduled_fte:0};a.required_fte+=r.required_fte||0;a.scheduled_fte+=r.scheduled_fte||0});barChart(c2,Object.values(agg),{label:"staff_type",key:"scheduled_fte",secondaryKey:"required_fte"});grid.append(p1,p2);
  const p3=panel("Intervals requiring preparation","Exact Planning Group and Staff Type shortages","ACTION LIST");p3.classList.add("wide");p3.append(makeTable(data.actions,[{key:"date",label:"Date",format:shortDate},{key:"time",label:"Interval",format:time},{key:"planning_group",label:"Planning group",strong:true},{key:"staff_type",label:"Staff type"},{key:"required_fte",label:"Required",kind:"decimal",align:"right"},{key:"gross_fte",label:"Gross",kind:"decimal",align:"right"},{key:"time_off_fte",label:"PTO/Away",kind:"decimal",align:"right"},{key:"scheduled_fte",label:"Net scheduled",kind:"decimal",align:"right"},{key:"gap_fte",label:"Gap",kind:"decimal",align:"right",strong:true},{key:"evidence",label:"Evidence"}]));grid.append(p3);return grid}
function renderService(data){const grid=node("div","grid");const p1=panel("Intraday service level","Whole-day 15-minute view; no averaged percentages","SERVICE");const c1=node("div","chart");p1.append(c1);lineChart(c1,data.timeline,[{key:"service_level",color:"#007c83"},{key:"abandon_rate",color:"#d6a84b"}],{percent:true});p1.querySelector(".panel-head").append(legend([{label:"Service level",color:"#007c83"},{label:"Abandon rate",color:"#d6a84b"}]));
  const p2=panel("Service by Management LOB","RSA BE remains one combined SL result","LOB");const c2=node("div","chart");p2.append(c2);barChart(c2,data.by_lob,{label:"management_lob",key:"service_level",percent:true});grid.append(p1,p2);
  const p3=panel("Queue diagnosis","Drill-down only; management service remains at LOB grain","EVIDENCE");p3.classList.add("wide");p3.append(makeTable(data.queues,[{key:"management_lob",label:"LOB",strong:true},{key:"group",label:"Group"},{key:"queue",label:"Queue",strong:true},{key:"offered",label:"Offered",kind:"integer",align:"right"},{key:"answered",label:"Handled",kind:"integer",align:"right"},{key:"handled_in_sl",label:"In SL",kind:"integer",align:"right"},{key:"abandoned",label:"Abandoned",kind:"integer",align:"right"},{key:"service_level",label:"SL",kind:"percent",align:"right"},{key:"abandon_rate",label:"Abandon",kind:"percent",align:"right"},{key:"aht_seconds",label:"AHT s",kind:"integer",align:"right"}]));grid.append(p3);return grid}
function segmentClass(seg){const c=String(seg.category||"").toLowerCase(),m=String(seg.mismatch||"").toLowerCase();if(m.includes("time_off"))return"seg-pto";if(seg.is_gap)return"seg-gap";if(c.includes("meal")||c.includes("lunch"))return"seg-meal";if(c.includes("break"))return"seg-break";if(c.includes("productive")||c.includes("auxiliary"))return"seg-logged";return"seg-off"}
function hourValue(value){if(!value)return 0;const part=value.includes("T")?value.slice(11,16):value.slice(-8,-3);const [h,m]=part.split(":").map(Number);return h+m/60}
function timeline(review){const list=node("div","seg-list");const leg=node("div","timeline-legend");[["Logged","seg-logged"],["Meal","seg-meal"],["Break","seg-break"],["Gap","seg-gap"],["PTO/Away","seg-pto"]].forEach(([label,cls])=>{const s=node("span");s.append(node("i",cls),document.createTextNode(label));leg.append(s)});list.append(leg);for(const row of review||[]){const item=node("div","agent-timeline");const meta=node("div","agent-meta");meta.append(node("b",null,row.agent||row.agent_id),node("span",null,`${row.management_lob||"—"} • ${row.classification||"Review"} • ${row.displaced_minutes} min`));const stack=node("div","timeline-stack");const sched=node("div","timeline-row");const s=node("span","scheduled");s.style.left=`${hourValue(row.scheduled_start)/24*100}%`;s.style.width=`${Math.max(0,hourValue(row.scheduled_end)-hourValue(row.scheduled_start))/24*100}%`;sched.append(s);const actual=node("div","timeline-row");for(const seg of row.segments||[]){const e=node("span",`segment ${segmentClass(seg)}`);const left=hourValue(seg.start),right=hourValue(seg.end);e.style.left=`${left/24*100}%`;e.style.width=`${Math.max(.15,right-left)/24*100}%`;e.title=`${time(seg.start)}–${time(seg.end)} ${seg.actual_status||seg.category||""}`;actual.append(e)}const labels=node("div","timeline-labels");["00","04","08","12","16","20","24"].forEach(v=>labels.append(node("span",null,v)));stack.append(sched,actual,labels);item.append(meta,stack);list.append(item)}if(!review?.length)empty(list,"No completed schedule-integrity case requires review.");return list}
function renderAttendance(data){const grid=node("div","grid");const p1=panel("Schedule over observed status","Schedule first; actual status and exact gaps directly below","TIMELINE");p1.append(timeline(data.review));const p2=panel("Treatment queue","Residual gaps and break/meal exceptions","REVIEW");const tabs=node("div","tabs");const tg=node("button","tab active","Residual gaps"),tb=node("button","tab","Break / meal");tabs.append(tg,tb);p2.querySelector(".panel-head").append(tabs);const gaps=makeTable(data.gaps,[{key:"date",label:"Date",format:shortDate},{key:"agent",label:"Agent",strong:true},{key:"start",label:"Start",format:time},{key:"end",label:"End",format:time},{key:"minutes",label:"Min",kind:"integer",align:"right"},{key:"issue",label:"Issue",pill:()=>"red"}]);const breaks=makeTable(data.break_meal,[{key:"date",label:"Date",format:shortDate},{key:"agent",label:"Agent",strong:true},{key:"break_minutes",label:"Break",kind:"integer",align:"right"},{key:"break_overrun",label:"Over",kind:"integer",align:"right"},{key:"meal_minutes",label:"Meal",kind:"integer",align:"right"},{key:"meal_overrun",label:"Over",kind:"integer",align:"right"}]);breaks.classList.add("hidden");tg.onclick=()=>{tg.classList.add("active");tb.classList.remove("active");gaps.classList.remove("hidden");breaks.classList.add("hidden")};tb.onclick=()=>{tb.classList.add("active");tg.classList.remove("active");breaks.classList.remove("hidden");gaps.classList.add("hidden")};p2.append(gaps,breaks);grid.append(p1,p2);
  const p3=panel("Exact residual intervals","These disappear only when refreshed final Verint Activities covers them","VERINT REVIEW");p3.classList.add("wide");p3.append(makeTable(data.gaps,[{key:"date",label:"Date",format:shortDate},{key:"management_lob",label:"LOB"},{key:"team_leader",label:"Team leader"},{key:"agent",label:"Agent",strong:true},{key:"agent_id",label:"Client ID"},{key:"start",label:"Gap start",format:v=>`${shortDate(v)} ${time(v)}`},{key:"end",label:"Gap end",format:v=>`${shortDate(v)} ${time(v)}`},{key:"minutes",label:"Minutes",kind:"integer",align:"right",strong:true},{key:"issue",label:"Incoherence"},{key:"suggested_activity",label:"Suggested activity"},{key:"reconciliation",label:"Verint check",pill:v=>String(v||"").includes("COVER")?"green":"amber"},{key:"source",label:"Observed source"}]));grid.append(p3);return grid}
function renderHistory(data){const grid=node("div","grid");const p1=panel("Service and final absence trend","Final absence and shrinkage use Verint Activities only","OUTCOME");const c1=node("div","chart");p1.append(c1);lineChart(c1,data.daily,[{key:"service_level",color:"#007c83"},{key:"absence_rate",color:"#b42318"},{key:"shrinkage_rate",color:"#d6a84b"}],{xKey:"date",percent:true});p1.querySelector(".panel-head").append(legend([{label:"SL",color:"#007c83"},{label:"Final absence",color:"#b42318"},{label:"Final shrinkage",color:"#d6a84b"}]));
  const p2=panel("Capacity delivery","Required, net scheduled, observed and productive FTE hours","CAPACITY");const c2=node("div","chart");p2.append(c2);lineChart(c2,data.daily,[{key:"required_fte_hours",color:"#b42318"},{key:"scheduled_fte_hours",color:"#007c83"},{key:"observed_fte_hours",color:"#d6a84b"},{key:"productive_fte_hours",color:"#1f7a53"}],{xKey:"date"});grid.append(p1,p2);
  const p3=panel("Repeated schedule-placement patterns","Evidence for management review; not an intent judgment","PATTERNS");p3.classList.add("wide");p3.append(makeTable(data.patterns,[{key:"date",label:"Latest day",format:shortDate},{key:"management_lob",label:"LOB"},{key:"team_leader",label:"Team leader"},{key:"agent",label:"Agent",strong:true},{key:"agent_id",label:"Client ID"},{key:"classification",label:"Classification",pill:resultPill},{key:"pattern",label:"Pattern"},{key:"recurrence",label:"Repeated",kind:"integer",align:"right"},{key:"eligible_days",label:"Eligible days",kind:"integer",align:"right"},{key:"displaced_minutes",label:"Minutes",kind:"integer",align:"right"},{key:"confidence",label:"Evidence",pill:v=>String(v).toLowerCase().includes("high")?"green":"amber"}]));grid.append(p3);return grid}

async function loadView(){
  const workspace=$("workspace");workspace.replaceChildren();const l=node("div","loading-card");l.append(node("span","spinner"),node("b",null,"Reading governed marts"),node("small",null,"No raw extracts are opened by this screen."));workspace.append(l);$("cards").replaceChildren();
  const config=pages[state.view];$("page-title").textContent=config.title;$("page-kicker").textContent=config.kicker;$("page-subtitle").textContent=config.subtitle;document.querySelectorAll(".nav-item").forEach(b=>b.classList.toggle("active",b.dataset.view===state.view));
  try{const data=await api(`/api/view/${state.view}?${query()}`);state.data=data;renderCards(data.cards);const renderer={today:renderToday,staffing:renderStaffing,service:renderService,attendance:renderAttendance,history:renderHistory}[state.view];workspace.replaceChildren(renderer(data));const q=query();$("scope-text").textContent=`${$("start").value} → ${$("end").value}  •  ${selected("lob")||"All management LOBs"}  •  ${selected("planning")||"All planning groups"}  •  ${selected("leader")||"All team leaders"}`;history.replaceState(null,"",`#${state.view}?${q}`)}catch(err){workspace.replaceChildren();const e=node("div","loading-card");e.append(node("b",null,"This view could not be loaded"),node("small",null,err.message));workspace.append(e);showToast(err.message,true)}
}
async function loadMeta(){try{state.meta=await api("/api/meta");$("data-through").textContent=state.meta.latest_date;$("footer-version").textContent=`WFMHub ${state.meta.version}`;$("state-dot").style.background=state.meta.last_refresh.status==="SUCCESS"?"#1f7a53":"#a65f00";$("refresh-text").textContent=`Database ${state.meta.database} • last update ${state.meta.last_refresh.finished_at?state.meta.last_refresh.finished_at.replace("T"," ").slice(0,16):"not run"}`;setSelect("lob",state.meta.management_lobs,state.meta.management_lobs[0],{allowAll:false});cascade("lob");setPeriod("latest");await loadView()}catch(err){showToast(err.message,true);$("workspace").textContent=err.message}}
async function startUpdate(){const d=$("update-dialog");if(!d.open)d.showModal();try{await api("/api/refresh",{method:"POST",headers:{"Content-Type":"application/json","X-WFMHub-Action":"refresh"},body:"{}"})}catch(err){if(!err.message.includes("409"))showToast(err.message,true)}pollUpdate()}
async function pollUpdate(){clearTimeout(state.timer);try{const s=await api("/api/refresh");$("update-status").textContent=s.status==="RUNNING"?"WFMHub is ingesting, validating and rebuilding governed marts…":`Update ${s.status.toLowerCase()}`;$("update-log").textContent=(s.lines||[]).join("\n");$("update-log").scrollTop=$("update-log").scrollHeight;let width=s.status==="RUNNING"?Math.min(88,12+(s.lines||[]).length*2.5):100;$("progress-bar").style.width=`${width}%`;$("progress-bar").style.background=s.status==="ERROR"?"#b42318":"#007c83";if(s.status==="RUNNING")state.timer=setTimeout(pollUpdate,1400);else if(s.status!=="IDLE"){await loadMeta();showToast(s.status==="SUCCESS"?"WFMHub data updated":"Update failed; inspect the log",s.status!=="SUCCESS")}}catch(err){showToast(err.message,true)}}

document.addEventListener("DOMContentLoaded",()=>{
  const hash=location.hash.slice(1).split("?")[0];if(pages[hash])state.view=hash;
  document.querySelectorAll(".nav-item").forEach(b=>b.addEventListener("click",()=>{state.view=b.dataset.view;loadView()}));
  $("period").addEventListener("change",()=>{setPeriod($("period").value);loadView()});
  for(const id of ["start","end"]){$(id).addEventListener("change",()=>{$("period").value="custom";loadView()})}
  for(const id of ["lob","planning","staff","leader","agent"]){$(id).addEventListener("change",()=>{cascade(id);loadView()})}
  $("reset-btn").onclick=()=>{$("period").value="latest";setSelect("lob",state.meta.management_lobs,state.meta.management_lobs[0],{allowAll:false});cascade("lob");setPeriod("latest");loadView()};
  $("export-btn").onclick=()=>{location.href=`/api/export/${state.view}?${query()}`};$("update-btn").onclick=startUpdate;$("dialog-close").onclick=()=>$("update-dialog").close();
  loadMeta();
});
